namespace ERP_System.GUI.Components
{
    partial class AddEditProdForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(AddEditProdForm));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties37 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties38 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties39 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties40 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties33 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties34 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties35 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties36 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties29 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties30 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties31 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties32 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.btnSearch = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuButton1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnAddEdit = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.label1 = new System.Windows.Forms.Label();
            this.txtSupID = new Bunifu.UI.WinForms.BunifuTextBox();
            this.lblTitle = new System.Windows.Forms.Label();
            this.lblName = new System.Windows.Forms.Label();
            this.txtName = new Bunifu.UI.WinForms.BunifuTextBox();
            this.lblDepartment = new System.Windows.Forms.Label();
            this.txtCategory = new Bunifu.UI.WinForms.BunifuTextBox();
            this.lblDesc = new System.Windows.Forms.Label();
            this.txtDesc = new Bunifu.UI.WinForms.BunifuTextBox();
            this.lblSalary = new System.Windows.Forms.Label();
            this.txtPurPrice = new Bunifu.UI.WinForms.BunifuTextBox();
            this.pnlDialog = new Bunifu.UI.WinForms.BunifuPanel();
            this.label2 = new System.Windows.Forms.Label();
            this.txtSku = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label3 = new System.Windows.Forms.Label();
            this.txtSalePrice = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label4 = new System.Windows.Forms.Label();
            this.txtThres = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label5 = new System.Windows.Forms.Label();
            this.txtStock = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label6 = new System.Windows.Forms.Label();
            this.txtSupName = new Bunifu.UI.WinForms.BunifuTextBox();
            this.pnlDialog.SuspendLayout();
            this.SuspendLayout();
            // 
            // btnSearch
            // 
            this.btnSearch.AllowAnimations = true;
            this.btnSearch.AllowMouseEffects = true;
            this.btnSearch.AllowToggling = false;
            this.btnSearch.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btnSearch.AnimationSpeed = 200;
            this.btnSearch.AutoGenerateColors = false;
            this.btnSearch.AutoRoundBorders = false;
            this.btnSearch.AutoSizeLeftIcon = true;
            this.btnSearch.AutoSizeRightIcon = true;
            this.btnSearch.BackColor = System.Drawing.Color.Transparent;
            this.btnSearch.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(120)))), ((int)(((byte)(215)))));
            this.btnSearch.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnSearch.BackgroundImage")));
            this.btnSearch.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSearch.ButtonText = "Search";
            this.btnSearch.ButtonTextMarginLeft = 0;
            this.btnSearch.ColorContrastOnClick = 45;
            this.btnSearch.ColorContrastOnHover = 45;
            this.btnSearch.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnSearch.CustomizableEdges = borderEdges1;
            this.btnSearch.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnSearch.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSearch.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnSearch.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnSearch.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnSearch.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Bold);
            this.btnSearch.ForeColor = System.Drawing.Color.White;
            this.btnSearch.IconLeft = null;
            this.btnSearch.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnSearch.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnSearch.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnSearch.IconMarginLeft = 11;
            this.btnSearch.IconPadding = 10;
            this.btnSearch.IconRight = null;
            this.btnSearch.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnSearch.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnSearch.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnSearch.IconSize = 25;
            this.btnSearch.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(120)))), ((int)(((byte)(215)))));
            this.btnSearch.IdleBorderRadius = 6;
            this.btnSearch.IdleBorderThickness = 1;
            this.btnSearch.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(120)))), ((int)(((byte)(215)))));
            this.btnSearch.IdleIconLeftImage = null;
            this.btnSearch.IdleIconRightImage = null;
            this.btnSearch.IndicateFocus = false;
            this.btnSearch.Location = new System.Drawing.Point(295, 109);
            this.btnSearch.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.btnSearch.Name = "btnSearch";
            this.btnSearch.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSearch.OnDisabledState.BorderRadius = 15;
            this.btnSearch.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSearch.OnDisabledState.BorderThickness = 1;
            this.btnSearch.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSearch.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSearch.OnDisabledState.IconLeftImage = null;
            this.btnSearch.OnDisabledState.IconRightImage = null;
            this.btnSearch.onHoverState.BorderColor = System.Drawing.Color.Transparent;
            this.btnSearch.onHoverState.BorderRadius = 15;
            this.btnSearch.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSearch.onHoverState.BorderThickness = 1;
            this.btnSearch.onHoverState.FillColor = System.Drawing.Color.DimGray;
            this.btnSearch.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnSearch.onHoverState.IconLeftImage = null;
            this.btnSearch.onHoverState.IconRightImage = null;
            this.btnSearch.OnIdleState.BorderColor = System.Drawing.Color.Black;
            this.btnSearch.OnIdleState.BorderRadius = 15;
            this.btnSearch.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSearch.OnIdleState.BorderThickness = 1;
            this.btnSearch.OnIdleState.FillColor = System.Drawing.Color.Black;
            this.btnSearch.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnSearch.OnIdleState.IconLeftImage = null;
            this.btnSearch.OnIdleState.IconRightImage = null;
            this.btnSearch.OnPressedState.BorderColor = System.Drawing.Color.Transparent;
            this.btnSearch.OnPressedState.BorderRadius = 15;
            this.btnSearch.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSearch.OnPressedState.BorderThickness = 1;
            this.btnSearch.OnPressedState.FillColor = System.Drawing.Color.Black;
            this.btnSearch.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnSearch.OnPressedState.IconLeftImage = null;
            this.btnSearch.OnPressedState.IconRightImage = null;
            this.btnSearch.Size = new System.Drawing.Size(106, 32);
            this.btnSearch.TabIndex = 22;
            this.btnSearch.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnSearch.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnSearch.TextMarginLeft = 0;
            this.btnSearch.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnSearch.UseDefaultRadiusAndThickness = true;
            this.btnSearch.Click += new System.EventHandler(this.SearchSupplier_Click);
            // 
            // bunifuButton1
            // 
            this.bunifuButton1.AllowAnimations = true;
            this.bunifuButton1.AllowMouseEffects = true;
            this.bunifuButton1.AllowToggling = false;
            this.bunifuButton1.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.bunifuButton1.AnimationSpeed = 200;
            this.bunifuButton1.AutoGenerateColors = false;
            this.bunifuButton1.AutoRoundBorders = false;
            this.bunifuButton1.AutoSizeLeftIcon = true;
            this.bunifuButton1.AutoSizeRightIcon = true;
            this.bunifuButton1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton1.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(120)))), ((int)(((byte)(215)))));
            this.bunifuButton1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton1.BackgroundImage")));
            this.bunifuButton1.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.ButtonText = "Cancel";
            this.bunifuButton1.ButtonTextMarginLeft = 0;
            this.bunifuButton1.ColorContrastOnClick = 45;
            this.bunifuButton1.ColorContrastOnHover = 45;
            this.bunifuButton1.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.bunifuButton1.CustomizableEdges = borderEdges2;
            this.bunifuButton1.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton1.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton1.DisabledFillColor = System.Drawing.Color.Empty;
            this.bunifuButton1.DisabledForecolor = System.Drawing.Color.Empty;
            this.bunifuButton1.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButton1.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Bold);
            this.bunifuButton1.ForeColor = System.Drawing.Color.Black;
            this.bunifuButton1.IconLeft = null;
            this.bunifuButton1.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton1.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.bunifuButton1.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton1.IconMarginLeft = 11;
            this.bunifuButton1.IconPadding = 10;
            this.bunifuButton1.IconRight = null;
            this.bunifuButton1.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton1.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.bunifuButton1.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton1.IconSize = 25;
            this.bunifuButton1.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(120)))), ((int)(((byte)(215)))));
            this.bunifuButton1.IdleBorderRadius = 6;
            this.bunifuButton1.IdleBorderThickness = 1;
            this.bunifuButton1.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(120)))), ((int)(((byte)(215)))));
            this.bunifuButton1.IdleIconLeftImage = null;
            this.bunifuButton1.IdleIconRightImage = null;
            this.bunifuButton1.IndicateFocus = false;
            this.bunifuButton1.Location = new System.Drawing.Point(346, 566);
            this.bunifuButton1.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.bunifuButton1.Name = "bunifuButton1";
            this.bunifuButton1.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton1.OnDisabledState.BorderRadius = 15;
            this.bunifuButton1.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnDisabledState.BorderThickness = 2;
            this.bunifuButton1.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton1.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton1.OnDisabledState.IconLeftImage = null;
            this.bunifuButton1.OnDisabledState.IconRightImage = null;
            this.bunifuButton1.onHoverState.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuButton1.onHoverState.BorderRadius = 15;
            this.bunifuButton1.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.onHoverState.BorderThickness = 2;
            this.bunifuButton1.onHoverState.FillColor = System.Drawing.Color.DimGray;
            this.bunifuButton1.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.onHoverState.IconLeftImage = null;
            this.bunifuButton1.onHoverState.IconRightImage = null;
            this.bunifuButton1.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.bunifuButton1.OnIdleState.BorderRadius = 15;
            this.bunifuButton1.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnIdleState.BorderThickness = 2;
            this.bunifuButton1.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.bunifuButton1.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.bunifuButton1.OnIdleState.IconLeftImage = null;
            this.bunifuButton1.OnIdleState.IconRightImage = null;
            this.bunifuButton1.OnPressedState.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuButton1.OnPressedState.BorderRadius = 15;
            this.bunifuButton1.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnPressedState.BorderThickness = 2;
            this.bunifuButton1.OnPressedState.FillColor = System.Drawing.Color.Black;
            this.bunifuButton1.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.OnPressedState.IconLeftImage = null;
            this.bunifuButton1.OnPressedState.IconRightImage = null;
            this.bunifuButton1.Size = new System.Drawing.Size(149, 41);
            this.bunifuButton1.TabIndex = 19;
            this.bunifuButton1.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton1.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton1.TextMarginLeft = 0;
            this.bunifuButton1.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton1.UseDefaultRadiusAndThickness = true;
            // 
            // btnAddEdit
            // 
            this.btnAddEdit.AllowAnimations = true;
            this.btnAddEdit.AllowMouseEffects = true;
            this.btnAddEdit.AllowToggling = false;
            this.btnAddEdit.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btnAddEdit.AnimationSpeed = 200;
            this.btnAddEdit.AutoGenerateColors = false;
            this.btnAddEdit.AutoRoundBorders = false;
            this.btnAddEdit.AutoSizeLeftIcon = true;
            this.btnAddEdit.AutoSizeRightIcon = true;
            this.btnAddEdit.BackColor = System.Drawing.Color.Transparent;
            this.btnAddEdit.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(120)))), ((int)(((byte)(215)))));
            this.btnAddEdit.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnAddEdit.BackgroundImage")));
            this.btnAddEdit.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAddEdit.ButtonText = "Add Product";
            this.btnAddEdit.ButtonTextMarginLeft = 0;
            this.btnAddEdit.ColorContrastOnClick = 45;
            this.btnAddEdit.ColorContrastOnHover = 45;
            this.btnAddEdit.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btnAddEdit.CustomizableEdges = borderEdges3;
            this.btnAddEdit.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnAddEdit.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnAddEdit.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnAddEdit.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnAddEdit.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnAddEdit.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Bold);
            this.btnAddEdit.ForeColor = System.Drawing.Color.White;
            this.btnAddEdit.IconLeft = null;
            this.btnAddEdit.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnAddEdit.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnAddEdit.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnAddEdit.IconMarginLeft = 11;
            this.btnAddEdit.IconPadding = 10;
            this.btnAddEdit.IconRight = null;
            this.btnAddEdit.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnAddEdit.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnAddEdit.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnAddEdit.IconSize = 25;
            this.btnAddEdit.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(120)))), ((int)(((byte)(215)))));
            this.btnAddEdit.IdleBorderRadius = 6;
            this.btnAddEdit.IdleBorderThickness = 1;
            this.btnAddEdit.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(120)))), ((int)(((byte)(215)))));
            this.btnAddEdit.IdleIconLeftImage = null;
            this.btnAddEdit.IdleIconRightImage = null;
            this.btnAddEdit.IndicateFocus = false;
            this.btnAddEdit.Location = new System.Drawing.Point(501, 566);
            this.btnAddEdit.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.btnAddEdit.Name = "btnAddEdit";
            this.btnAddEdit.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnAddEdit.OnDisabledState.BorderRadius = 15;
            this.btnAddEdit.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAddEdit.OnDisabledState.BorderThickness = 1;
            this.btnAddEdit.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnAddEdit.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnAddEdit.OnDisabledState.IconLeftImage = null;
            this.btnAddEdit.OnDisabledState.IconRightImage = null;
            this.btnAddEdit.onHoverState.BorderColor = System.Drawing.Color.Transparent;
            this.btnAddEdit.onHoverState.BorderRadius = 15;
            this.btnAddEdit.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAddEdit.onHoverState.BorderThickness = 1;
            this.btnAddEdit.onHoverState.FillColor = System.Drawing.Color.DimGray;
            this.btnAddEdit.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnAddEdit.onHoverState.IconLeftImage = null;
            this.btnAddEdit.onHoverState.IconRightImage = null;
            this.btnAddEdit.OnIdleState.BorderColor = System.Drawing.Color.Black;
            this.btnAddEdit.OnIdleState.BorderRadius = 15;
            this.btnAddEdit.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAddEdit.OnIdleState.BorderThickness = 1;
            this.btnAddEdit.OnIdleState.FillColor = System.Drawing.Color.Black;
            this.btnAddEdit.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnAddEdit.OnIdleState.IconLeftImage = null;
            this.btnAddEdit.OnIdleState.IconRightImage = null;
            this.btnAddEdit.OnPressedState.BorderColor = System.Drawing.Color.Transparent;
            this.btnAddEdit.OnPressedState.BorderRadius = 15;
            this.btnAddEdit.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAddEdit.OnPressedState.BorderThickness = 1;
            this.btnAddEdit.OnPressedState.FillColor = System.Drawing.Color.Black;
            this.btnAddEdit.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnAddEdit.OnPressedState.IconLeftImage = null;
            this.btnAddEdit.OnPressedState.IconRightImage = null;
            this.btnAddEdit.Size = new System.Drawing.Size(149, 41);
            this.btnAddEdit.TabIndex = 18;
            this.btnAddEdit.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnAddEdit.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnAddEdit.TextMarginLeft = 0;
            this.btnAddEdit.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnAddEdit.UseDefaultRadiusAndThickness = true;
            // 
            // label1
            // 
            this.label1.BackColor = System.Drawing.Color.Transparent;
            this.label1.Font = new System.Drawing.Font("Segoe UI", 10.944F, System.Drawing.FontStyle.Bold);
            this.label1.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(50)))), ((int)(((byte)(58)))));
            this.label1.Location = new System.Drawing.Point(26, 83);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(131, 23);
            this.label1.TabIndex = 14;
            this.label1.Text = "Supplier ID";
            // 
            // txtSupID
            // 
            this.txtSupID.AcceptsReturn = false;
            this.txtSupID.AcceptsTab = false;
            this.txtSupID.AnimationSpeed = 200;
            this.txtSupID.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtSupID.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtSupID.AutoSizeHeight = true;
            this.txtSupID.BackColor = System.Drawing.Color.Transparent;
            this.txtSupID.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtSupID.BackgroundImage")));
            this.txtSupID.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtSupID.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtSupID.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtSupID.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtSupID.BorderRadius = 5;
            this.txtSupID.BorderThickness = 1;
            this.txtSupID.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtSupID.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtSupID.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSupID.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtSupID.DefaultText = "";
            this.txtSupID.FillColor = System.Drawing.Color.Gainsboro;
            this.txtSupID.HideSelection = true;
            this.txtSupID.IconLeft = null;
            this.txtSupID.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSupID.IconPadding = 10;
            this.txtSupID.IconRight = null;
            this.txtSupID.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSupID.Lines = new string[0];
            this.txtSupID.Location = new System.Drawing.Point(31, 109);
            this.txtSupID.MaxLength = 32767;
            this.txtSupID.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtSupID.Modified = false;
            this.txtSupID.Multiline = false;
            this.txtSupID.Name = "txtSupID";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSupID.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtSupID.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSupID.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.Gainsboro;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSupID.OnIdleState = stateProperties4;
            this.txtSupID.Padding = new System.Windows.Forms.Padding(3);
            this.txtSupID.PasswordChar = '\0';
            this.txtSupID.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.txtSupID.PlaceholderText = "Enter Supplier ID";
            this.txtSupID.ReadOnly = false;
            this.txtSupID.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtSupID.SelectedText = "";
            this.txtSupID.SelectionLength = 0;
            this.txtSupID.SelectionStart = 0;
            this.txtSupID.ShortcutsEnabled = true;
            this.txtSupID.Size = new System.Drawing.Size(234, 32);
            this.txtSupID.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtSupID.TabIndex = 13;
            this.txtSupID.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtSupID.TextMarginBottom = 0;
            this.txtSupID.TextMarginLeft = 3;
            this.txtSupID.TextMarginTop = 1;
            this.txtSupID.TextPlaceholder = "Enter Supplier ID";
            this.txtSupID.UseSystemPasswordChar = false;
            this.txtSupID.WordWrap = true;
            // 
            // lblTitle
            // 
            this.lblTitle.BackColor = System.Drawing.Color.Transparent;
            this.lblTitle.Font = new System.Drawing.Font("Segoe UI Semibold", 14F, System.Drawing.FontStyle.Bold);
            this.lblTitle.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(50)))), ((int)(((byte)(58)))));
            this.lblTitle.Location = new System.Drawing.Point(225, 9);
            this.lblTitle.Name = "lblTitle";
            this.lblTitle.Size = new System.Drawing.Size(186, 33);
            this.lblTitle.TabIndex = 0;
            this.lblTitle.Text = "Add Product";
            // 
            // lblName
            // 
            this.lblName.BackColor = System.Drawing.Color.Transparent;
            this.lblName.Font = new System.Drawing.Font("Segoe UI", 10.944F, System.Drawing.FontStyle.Bold);
            this.lblName.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(50)))), ((int)(((byte)(58)))));
            this.lblName.Location = new System.Drawing.Point(30, 315);
            this.lblName.Name = "lblName";
            this.lblName.Size = new System.Drawing.Size(110, 23);
            this.lblName.TabIndex = 1;
            this.lblName.Text = " Name";
            // 
            // txtName
            // 
            this.txtName.AcceptsReturn = false;
            this.txtName.AcceptsTab = false;
            this.txtName.AnimationSpeed = 200;
            this.txtName.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtName.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtName.AutoSizeHeight = true;
            this.txtName.BackColor = System.Drawing.Color.Transparent;
            this.txtName.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtName.BackgroundImage")));
            this.txtName.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtName.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtName.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtName.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtName.BorderRadius = 5;
            this.txtName.BorderThickness = 1;
            this.txtName.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtName.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtName.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtName.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtName.DefaultText = "";
            this.txtName.FillColor = System.Drawing.Color.Gainsboro;
            this.txtName.HideSelection = true;
            this.txtName.IconLeft = null;
            this.txtName.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtName.IconPadding = 10;
            this.txtName.IconRight = null;
            this.txtName.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtName.Lines = new string[0];
            this.txtName.Location = new System.Drawing.Point(35, 351);
            this.txtName.MaxLength = 32767;
            this.txtName.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtName.Modified = false;
            this.txtName.Multiline = false;
            this.txtName.Name = "txtName";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtName.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtName.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtName.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.Gainsboro;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtName.OnIdleState = stateProperties8;
            this.txtName.Padding = new System.Windows.Forms.Padding(3);
            this.txtName.PasswordChar = '\0';
            this.txtName.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.txtName.PlaceholderText = "Enter full name";
            this.txtName.ReadOnly = false;
            this.txtName.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtName.SelectedText = "";
            this.txtName.SelectionLength = 0;
            this.txtName.SelectionStart = 0;
            this.txtName.ShortcutsEnabled = true;
            this.txtName.Size = new System.Drawing.Size(300, 32);
            this.txtName.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtName.TabIndex = 2;
            this.txtName.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtName.TextMarginBottom = 0;
            this.txtName.TextMarginLeft = 3;
            this.txtName.TextMarginTop = 1;
            this.txtName.TextPlaceholder = "Enter full name";
            this.txtName.UseSystemPasswordChar = false;
            this.txtName.WordWrap = true;
            // 
            // lblDepartment
            // 
            this.lblDepartment.BackColor = System.Drawing.Color.Transparent;
            this.lblDepartment.Font = new System.Drawing.Font("Segoe UI", 10.944F, System.Drawing.FontStyle.Bold);
            this.lblDepartment.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(50)))), ((int)(((byte)(58)))));
            this.lblDepartment.Location = new System.Drawing.Point(336, 315);
            this.lblDepartment.Name = "lblDepartment";
            this.lblDepartment.Size = new System.Drawing.Size(131, 23);
            this.lblDepartment.TabIndex = 3;
            this.lblDepartment.Text = "Category";
            // 
            // txtCategory
            // 
            this.txtCategory.AcceptsReturn = false;
            this.txtCategory.AcceptsTab = false;
            this.txtCategory.AnimationSpeed = 200;
            this.txtCategory.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtCategory.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtCategory.AutoSizeHeight = true;
            this.txtCategory.BackColor = System.Drawing.Color.Transparent;
            this.txtCategory.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtCategory.BackgroundImage")));
            this.txtCategory.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtCategory.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtCategory.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtCategory.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtCategory.BorderRadius = 5;
            this.txtCategory.BorderThickness = 1;
            this.txtCategory.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtCategory.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtCategory.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCategory.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtCategory.DefaultText = "";
            this.txtCategory.FillColor = System.Drawing.Color.Gainsboro;
            this.txtCategory.HideSelection = true;
            this.txtCategory.IconLeft = null;
            this.txtCategory.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCategory.IconPadding = 10;
            this.txtCategory.IconRight = null;
            this.txtCategory.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCategory.Lines = new string[0];
            this.txtCategory.Location = new System.Drawing.Point(341, 351);
            this.txtCategory.MaxLength = 32767;
            this.txtCategory.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtCategory.Modified = false;
            this.txtCategory.Multiline = false;
            this.txtCategory.Name = "txtCategory";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCategory.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtCategory.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCategory.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.Gainsboro;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCategory.OnIdleState = stateProperties12;
            this.txtCategory.Padding = new System.Windows.Forms.Padding(3);
            this.txtCategory.PasswordChar = '\0';
            this.txtCategory.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.txtCategory.PlaceholderText = "Enter Category";
            this.txtCategory.ReadOnly = false;
            this.txtCategory.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtCategory.SelectedText = "";
            this.txtCategory.SelectionLength = 0;
            this.txtCategory.SelectionStart = 0;
            this.txtCategory.ShortcutsEnabled = true;
            this.txtCategory.Size = new System.Drawing.Size(300, 32);
            this.txtCategory.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtCategory.TabIndex = 4;
            this.txtCategory.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtCategory.TextMarginBottom = 0;
            this.txtCategory.TextMarginLeft = 3;
            this.txtCategory.TextMarginTop = 1;
            this.txtCategory.TextPlaceholder = "Enter Category";
            this.txtCategory.UseSystemPasswordChar = false;
            this.txtCategory.WordWrap = true;
            // 
            // lblDesc
            // 
            this.lblDesc.BackColor = System.Drawing.Color.Transparent;
            this.lblDesc.Font = new System.Drawing.Font("Segoe UI", 10.944F, System.Drawing.FontStyle.Bold);
            this.lblDesc.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(50)))), ((int)(((byte)(58)))));
            this.lblDesc.Location = new System.Drawing.Point(26, 397);
            this.lblDesc.Name = "lblDesc";
            this.lblDesc.Size = new System.Drawing.Size(131, 23);
            this.lblDesc.TabIndex = 5;
            this.lblDesc.Text = "Description";
            // 
            // txtDesc
            // 
            this.txtDesc.AcceptsReturn = false;
            this.txtDesc.AcceptsTab = false;
            this.txtDesc.AnimationSpeed = 200;
            this.txtDesc.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtDesc.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtDesc.AutoSizeHeight = true;
            this.txtDesc.BackColor = System.Drawing.Color.Transparent;
            this.txtDesc.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtDesc.BackgroundImage")));
            this.txtDesc.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtDesc.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtDesc.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtDesc.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtDesc.BorderRadius = 5;
            this.txtDesc.BorderThickness = 1;
            this.txtDesc.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtDesc.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtDesc.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDesc.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtDesc.DefaultText = "";
            this.txtDesc.FillColor = System.Drawing.Color.Gainsboro;
            this.txtDesc.HideSelection = true;
            this.txtDesc.IconLeft = null;
            this.txtDesc.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDesc.IconPadding = 10;
            this.txtDesc.IconRight = null;
            this.txtDesc.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDesc.Lines = new string[0];
            this.txtDesc.Location = new System.Drawing.Point(31, 433);
            this.txtDesc.MaxLength = 32767;
            this.txtDesc.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtDesc.Modified = false;
            this.txtDesc.Multiline = false;
            this.txtDesc.Name = "txtDesc";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDesc.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtDesc.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDesc.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.Gainsboro;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDesc.OnIdleState = stateProperties16;
            this.txtDesc.Padding = new System.Windows.Forms.Padding(3);
            this.txtDesc.PasswordChar = '\0';
            this.txtDesc.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.txtDesc.PlaceholderText = "Enter  Description";
            this.txtDesc.ReadOnly = false;
            this.txtDesc.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtDesc.SelectedText = "";
            this.txtDesc.SelectionLength = 0;
            this.txtDesc.SelectionStart = 0;
            this.txtDesc.ShortcutsEnabled = true;
            this.txtDesc.Size = new System.Drawing.Size(300, 32);
            this.txtDesc.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtDesc.TabIndex = 6;
            this.txtDesc.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtDesc.TextMarginBottom = 0;
            this.txtDesc.TextMarginLeft = 3;
            this.txtDesc.TextMarginTop = 1;
            this.txtDesc.TextPlaceholder = "Enter  Description";
            this.txtDesc.UseSystemPasswordChar = false;
            this.txtDesc.WordWrap = true;
            // 
            // lblSalary
            // 
            this.lblSalary.BackColor = System.Drawing.Color.Transparent;
            this.lblSalary.Font = new System.Drawing.Font("Segoe UI", 10.944F, System.Drawing.FontStyle.Bold);
            this.lblSalary.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(50)))), ((int)(((byte)(58)))));
            this.lblSalary.Location = new System.Drawing.Point(26, 480);
            this.lblSalary.Name = "lblSalary";
            this.lblSalary.Size = new System.Drawing.Size(168, 23);
            this.lblSalary.TabIndex = 7;
            this.lblSalary.Text = "Purchase Price";
            // 
            // txtPurPrice
            // 
            this.txtPurPrice.AcceptsReturn = false;
            this.txtPurPrice.AcceptsTab = false;
            this.txtPurPrice.AnimationSpeed = 200;
            this.txtPurPrice.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtPurPrice.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtPurPrice.AutoSizeHeight = true;
            this.txtPurPrice.BackColor = System.Drawing.Color.Transparent;
            this.txtPurPrice.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtPurPrice.BackgroundImage")));
            this.txtPurPrice.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtPurPrice.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtPurPrice.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtPurPrice.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtPurPrice.BorderRadius = 5;
            this.txtPurPrice.BorderThickness = 1;
            this.txtPurPrice.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtPurPrice.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtPurPrice.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPurPrice.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtPurPrice.DefaultText = "";
            this.txtPurPrice.FillColor = System.Drawing.Color.Gainsboro;
            this.txtPurPrice.HideSelection = true;
            this.txtPurPrice.IconLeft = null;
            this.txtPurPrice.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPurPrice.IconPadding = 10;
            this.txtPurPrice.IconRight = null;
            this.txtPurPrice.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPurPrice.Lines = new string[0];
            this.txtPurPrice.Location = new System.Drawing.Point(31, 515);
            this.txtPurPrice.MaxLength = 32767;
            this.txtPurPrice.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtPurPrice.Modified = false;
            this.txtPurPrice.Multiline = false;
            this.txtPurPrice.Name = "txtPurPrice";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPurPrice.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtPurPrice.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPurPrice.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.Gainsboro;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPurPrice.OnIdleState = stateProperties20;
            this.txtPurPrice.Padding = new System.Windows.Forms.Padding(3);
            this.txtPurPrice.PasswordChar = '\0';
            this.txtPurPrice.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.txtPurPrice.PlaceholderText = "Enter Purchase Price";
            this.txtPurPrice.ReadOnly = false;
            this.txtPurPrice.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtPurPrice.SelectedText = "";
            this.txtPurPrice.SelectionLength = 0;
            this.txtPurPrice.SelectionStart = 0;
            this.txtPurPrice.ShortcutsEnabled = true;
            this.txtPurPrice.Size = new System.Drawing.Size(175, 32);
            this.txtPurPrice.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtPurPrice.TabIndex = 8;
            this.txtPurPrice.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtPurPrice.TextMarginBottom = 0;
            this.txtPurPrice.TextMarginLeft = 3;
            this.txtPurPrice.TextMarginTop = 1;
            this.txtPurPrice.TextPlaceholder = "Enter Purchase Price";
            this.txtPurPrice.UseSystemPasswordChar = false;
            this.txtPurPrice.WordWrap = true;
            // 
            // pnlDialog
            // 
            this.pnlDialog.BackgroundColor = System.Drawing.Color.White;
            this.pnlDialog.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("pnlDialog.BackgroundImage")));
            this.pnlDialog.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.pnlDialog.BorderColor = System.Drawing.Color.LightGray;
            this.pnlDialog.BorderRadius = 20;
            this.pnlDialog.BorderThickness = 1;
            this.pnlDialog.Controls.Add(this.label6);
            this.pnlDialog.Controls.Add(this.txtSupName);
            this.pnlDialog.Controls.Add(this.label5);
            this.pnlDialog.Controls.Add(this.txtStock);
            this.pnlDialog.Controls.Add(this.label4);
            this.pnlDialog.Controls.Add(this.txtThres);
            this.pnlDialog.Controls.Add(this.label3);
            this.pnlDialog.Controls.Add(this.txtSalePrice);
            this.pnlDialog.Controls.Add(this.label2);
            this.pnlDialog.Controls.Add(this.txtSku);
            this.pnlDialog.Controls.Add(this.btnSearch);
            this.pnlDialog.Controls.Add(this.bunifuButton1);
            this.pnlDialog.Controls.Add(this.btnAddEdit);
            this.pnlDialog.Controls.Add(this.label1);
            this.pnlDialog.Controls.Add(this.txtSupID);
            this.pnlDialog.Controls.Add(this.lblTitle);
            this.pnlDialog.Controls.Add(this.lblName);
            this.pnlDialog.Controls.Add(this.txtName);
            this.pnlDialog.Controls.Add(this.lblDepartment);
            this.pnlDialog.Controls.Add(this.txtCategory);
            this.pnlDialog.Controls.Add(this.lblDesc);
            this.pnlDialog.Controls.Add(this.txtDesc);
            this.pnlDialog.Controls.Add(this.lblSalary);
            this.pnlDialog.Controls.Add(this.txtPurPrice);
            this.pnlDialog.Dock = System.Windows.Forms.DockStyle.Fill;
            this.pnlDialog.Location = new System.Drawing.Point(0, 0);
            this.pnlDialog.Name = "pnlDialog";
            this.pnlDialog.ShowBorders = true;
            this.pnlDialog.Size = new System.Drawing.Size(665, 629);
            this.pnlDialog.TabIndex = 1;
            // 
            // label2
            // 
            this.label2.BackColor = System.Drawing.Color.Transparent;
            this.label2.Font = new System.Drawing.Font("Segoe UI", 10.944F, System.Drawing.FontStyle.Bold);
            this.label2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(50)))), ((int)(((byte)(58)))));
            this.label2.Location = new System.Drawing.Point(30, 233);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(110, 23);
            this.label2.TabIndex = 23;
            this.label2.Text = "SKU";
            // 
            // txtSku
            // 
            this.txtSku.AcceptsReturn = false;
            this.txtSku.AcceptsTab = false;
            this.txtSku.AnimationSpeed = 200;
            this.txtSku.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtSku.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtSku.AutoSizeHeight = true;
            this.txtSku.BackColor = System.Drawing.Color.Transparent;
            this.txtSku.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtSku.BackgroundImage")));
            this.txtSku.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtSku.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtSku.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtSku.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtSku.BorderRadius = 5;
            this.txtSku.BorderThickness = 1;
            this.txtSku.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtSku.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtSku.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSku.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtSku.DefaultText = "";
            this.txtSku.FillColor = System.Drawing.Color.Gainsboro;
            this.txtSku.HideSelection = true;
            this.txtSku.IconLeft = null;
            this.txtSku.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSku.IconPadding = 10;
            this.txtSku.IconRight = null;
            this.txtSku.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSku.Lines = new string[0];
            this.txtSku.Location = new System.Drawing.Point(31, 268);
            this.txtSku.MaxLength = 32767;
            this.txtSku.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtSku.Modified = false;
            this.txtSku.Multiline = false;
            this.txtSku.Name = "txtSku";
            stateProperties37.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties37.FillColor = System.Drawing.Color.Empty;
            stateProperties37.ForeColor = System.Drawing.Color.Empty;
            stateProperties37.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSku.OnActiveState = stateProperties37;
            stateProperties38.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties38.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties38.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties38.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtSku.OnDisabledState = stateProperties38;
            stateProperties39.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties39.FillColor = System.Drawing.Color.Empty;
            stateProperties39.ForeColor = System.Drawing.Color.Empty;
            stateProperties39.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSku.OnHoverState = stateProperties39;
            stateProperties40.BorderColor = System.Drawing.Color.Silver;
            stateProperties40.FillColor = System.Drawing.Color.Gainsboro;
            stateProperties40.ForeColor = System.Drawing.Color.Empty;
            stateProperties40.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSku.OnIdleState = stateProperties40;
            this.txtSku.Padding = new System.Windows.Forms.Padding(3);
            this.txtSku.PasswordChar = '\0';
            this.txtSku.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.txtSku.PlaceholderText = "Enter SKU";
            this.txtSku.ReadOnly = false;
            this.txtSku.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtSku.SelectedText = "";
            this.txtSku.SelectionLength = 0;
            this.txtSku.SelectionStart = 0;
            this.txtSku.ShortcutsEnabled = true;
            this.txtSku.Size = new System.Drawing.Size(300, 32);
            this.txtSku.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtSku.TabIndex = 24;
            this.txtSku.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtSku.TextMarginBottom = 0;
            this.txtSku.TextMarginLeft = 3;
            this.txtSku.TextMarginTop = 1;
            this.txtSku.TextPlaceholder = "Enter SKU";
            this.txtSku.UseSystemPasswordChar = false;
            this.txtSku.WordWrap = true;
            // 
            // label3
            // 
            this.label3.BackColor = System.Drawing.Color.Transparent;
            this.label3.Font = new System.Drawing.Font("Segoe UI", 10.944F, System.Drawing.FontStyle.Bold);
            this.label3.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(50)))), ((int)(((byte)(58)))));
            this.label3.Location = new System.Drawing.Point(222, 480);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(168, 23);
            this.label3.TabIndex = 25;
            this.label3.Text = "Sale Price";
            // 
            // txtSalePrice
            // 
            this.txtSalePrice.AcceptsReturn = false;
            this.txtSalePrice.AcceptsTab = false;
            this.txtSalePrice.AnimationSpeed = 200;
            this.txtSalePrice.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtSalePrice.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtSalePrice.AutoSizeHeight = true;
            this.txtSalePrice.BackColor = System.Drawing.Color.Transparent;
            this.txtSalePrice.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtSalePrice.BackgroundImage")));
            this.txtSalePrice.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtSalePrice.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtSalePrice.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtSalePrice.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtSalePrice.BorderRadius = 5;
            this.txtSalePrice.BorderThickness = 1;
            this.txtSalePrice.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtSalePrice.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtSalePrice.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSalePrice.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtSalePrice.DefaultText = "";
            this.txtSalePrice.FillColor = System.Drawing.Color.Gainsboro;
            this.txtSalePrice.HideSelection = true;
            this.txtSalePrice.IconLeft = null;
            this.txtSalePrice.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSalePrice.IconPadding = 10;
            this.txtSalePrice.IconRight = null;
            this.txtSalePrice.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSalePrice.Lines = new string[0];
            this.txtSalePrice.Location = new System.Drawing.Point(227, 515);
            this.txtSalePrice.MaxLength = 32767;
            this.txtSalePrice.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtSalePrice.Modified = false;
            this.txtSalePrice.Multiline = false;
            this.txtSalePrice.Name = "txtSalePrice";
            stateProperties33.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties33.FillColor = System.Drawing.Color.Empty;
            stateProperties33.ForeColor = System.Drawing.Color.Empty;
            stateProperties33.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSalePrice.OnActiveState = stateProperties33;
            stateProperties34.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties34.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties34.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties34.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtSalePrice.OnDisabledState = stateProperties34;
            stateProperties35.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties35.FillColor = System.Drawing.Color.Empty;
            stateProperties35.ForeColor = System.Drawing.Color.Empty;
            stateProperties35.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSalePrice.OnHoverState = stateProperties35;
            stateProperties36.BorderColor = System.Drawing.Color.Silver;
            stateProperties36.FillColor = System.Drawing.Color.Gainsboro;
            stateProperties36.ForeColor = System.Drawing.Color.Empty;
            stateProperties36.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSalePrice.OnIdleState = stateProperties36;
            this.txtSalePrice.Padding = new System.Windows.Forms.Padding(3);
            this.txtSalePrice.PasswordChar = '\0';
            this.txtSalePrice.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.txtSalePrice.PlaceholderText = "Enter Sale Price";
            this.txtSalePrice.ReadOnly = false;
            this.txtSalePrice.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtSalePrice.SelectedText = "";
            this.txtSalePrice.SelectionLength = 0;
            this.txtSalePrice.SelectionStart = 0;
            this.txtSalePrice.ShortcutsEnabled = true;
            this.txtSalePrice.Size = new System.Drawing.Size(175, 32);
            this.txtSalePrice.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtSalePrice.TabIndex = 26;
            this.txtSalePrice.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtSalePrice.TextMarginBottom = 0;
            this.txtSalePrice.TextMarginLeft = 3;
            this.txtSalePrice.TextMarginTop = 1;
            this.txtSalePrice.TextPlaceholder = "Enter Sale Price";
            this.txtSalePrice.UseSystemPasswordChar = false;
            this.txtSalePrice.WordWrap = true;
            // 
            // label4
            // 
            this.label4.BackColor = System.Drawing.Color.Transparent;
            this.label4.Font = new System.Drawing.Font("Segoe UI", 10.944F, System.Drawing.FontStyle.Bold);
            this.label4.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(50)))), ((int)(((byte)(58)))));
            this.label4.Location = new System.Drawing.Point(342, 397);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(225, 23);
            this.label4.TabIndex = 27;
            this.label4.Text = "Low Stock Threshold";
            // 
            // txtThres
            // 
            this.txtThres.AcceptsReturn = false;
            this.txtThres.AcceptsTab = false;
            this.txtThres.AnimationSpeed = 200;
            this.txtThres.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtThres.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtThres.AutoSizeHeight = true;
            this.txtThres.BackColor = System.Drawing.Color.Transparent;
            this.txtThres.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtThres.BackgroundImage")));
            this.txtThres.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtThres.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtThres.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtThres.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtThres.BorderRadius = 5;
            this.txtThres.BorderThickness = 1;
            this.txtThres.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtThres.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtThres.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtThres.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtThres.DefaultText = "";
            this.txtThres.FillColor = System.Drawing.Color.Gainsboro;
            this.txtThres.HideSelection = true;
            this.txtThres.IconLeft = null;
            this.txtThres.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtThres.IconPadding = 10;
            this.txtThres.IconRight = null;
            this.txtThres.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtThres.Lines = new string[0];
            this.txtThres.Location = new System.Drawing.Point(347, 433);
            this.txtThres.MaxLength = 32767;
            this.txtThres.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtThres.Modified = false;
            this.txtThres.Multiline = false;
            this.txtThres.Name = "txtThres";
            stateProperties29.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties29.FillColor = System.Drawing.Color.Empty;
            stateProperties29.ForeColor = System.Drawing.Color.Empty;
            stateProperties29.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtThres.OnActiveState = stateProperties29;
            stateProperties30.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties30.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties30.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties30.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtThres.OnDisabledState = stateProperties30;
            stateProperties31.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties31.FillColor = System.Drawing.Color.Empty;
            stateProperties31.ForeColor = System.Drawing.Color.Empty;
            stateProperties31.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtThres.OnHoverState = stateProperties31;
            stateProperties32.BorderColor = System.Drawing.Color.Silver;
            stateProperties32.FillColor = System.Drawing.Color.Gainsboro;
            stateProperties32.ForeColor = System.Drawing.Color.Empty;
            stateProperties32.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtThres.OnIdleState = stateProperties32;
            this.txtThres.Padding = new System.Windows.Forms.Padding(3);
            this.txtThres.PasswordChar = '\0';
            this.txtThres.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.txtThres.PlaceholderText = "Enter Threshold";
            this.txtThres.ReadOnly = false;
            this.txtThres.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtThres.SelectedText = "";
            this.txtThres.SelectionLength = 0;
            this.txtThres.SelectionStart = 0;
            this.txtThres.ShortcutsEnabled = true;
            this.txtThres.Size = new System.Drawing.Size(300, 32);
            this.txtThres.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtThres.TabIndex = 28;
            this.txtThres.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtThres.TextMarginBottom = 0;
            this.txtThres.TextMarginLeft = 3;
            this.txtThres.TextMarginTop = 1;
            this.txtThres.TextPlaceholder = "Enter Threshold";
            this.txtThres.UseSystemPasswordChar = false;
            this.txtThres.WordWrap = true;
            // 
            // label5
            // 
            this.label5.BackColor = System.Drawing.Color.Transparent;
            this.label5.Font = new System.Drawing.Font("Segoe UI", 10.944F, System.Drawing.FontStyle.Bold);
            this.label5.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(50)))), ((int)(((byte)(58)))));
            this.label5.Location = new System.Drawing.Point(419, 480);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(168, 23);
            this.label5.TabIndex = 29;
            this.label5.Text = "Stock";
            // 
            // txtStock
            // 
            this.txtStock.AcceptsReturn = false;
            this.txtStock.AcceptsTab = false;
            this.txtStock.AnimationSpeed = 200;
            this.txtStock.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtStock.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtStock.AutoSizeHeight = true;
            this.txtStock.BackColor = System.Drawing.Color.Transparent;
            this.txtStock.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtStock.BackgroundImage")));
            this.txtStock.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtStock.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtStock.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtStock.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtStock.BorderRadius = 5;
            this.txtStock.BorderThickness = 1;
            this.txtStock.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtStock.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtStock.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtStock.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtStock.DefaultText = "";
            this.txtStock.FillColor = System.Drawing.Color.Gainsboro;
            this.txtStock.HideSelection = true;
            this.txtStock.IconLeft = null;
            this.txtStock.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtStock.IconPadding = 10;
            this.txtStock.IconRight = null;
            this.txtStock.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtStock.Lines = new string[0];
            this.txtStock.Location = new System.Drawing.Point(424, 515);
            this.txtStock.MaxLength = 32767;
            this.txtStock.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtStock.Modified = false;
            this.txtStock.Multiline = false;
            this.txtStock.Name = "txtStock";
            stateProperties25.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtStock.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties26.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties26.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtStock.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtStock.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.Silver;
            stateProperties28.FillColor = System.Drawing.Color.Gainsboro;
            stateProperties28.ForeColor = System.Drawing.Color.Empty;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtStock.OnIdleState = stateProperties28;
            this.txtStock.Padding = new System.Windows.Forms.Padding(3);
            this.txtStock.PasswordChar = '\0';
            this.txtStock.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.txtStock.PlaceholderText = "Enter Stock";
            this.txtStock.ReadOnly = false;
            this.txtStock.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtStock.SelectedText = "";
            this.txtStock.SelectionLength = 0;
            this.txtStock.SelectionStart = 0;
            this.txtStock.ShortcutsEnabled = true;
            this.txtStock.Size = new System.Drawing.Size(175, 32);
            this.txtStock.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtStock.TabIndex = 30;
            this.txtStock.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtStock.TextMarginBottom = 0;
            this.txtStock.TextMarginLeft = 3;
            this.txtStock.TextMarginTop = 1;
            this.txtStock.TextPlaceholder = "Enter Stock";
            this.txtStock.UseSystemPasswordChar = false;
            this.txtStock.WordWrap = true;
            // 
            // label6
            // 
            this.label6.BackColor = System.Drawing.Color.Transparent;
            this.label6.Font = new System.Drawing.Font("Segoe UI", 10.944F, System.Drawing.FontStyle.Bold);
            this.label6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(50)))), ((int)(((byte)(58)))));
            this.label6.Location = new System.Drawing.Point(26, 151);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(110, 23);
            this.label6.TabIndex = 31;
            this.label6.Text = "Supplier";
            // 
            // txtSupName
            // 
            this.txtSupName.AcceptsReturn = false;
            this.txtSupName.AcceptsTab = false;
            this.txtSupName.AnimationSpeed = 200;
            this.txtSupName.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtSupName.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtSupName.AutoSizeHeight = true;
            this.txtSupName.BackColor = System.Drawing.Color.Transparent;
            this.txtSupName.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtSupName.BackgroundImage")));
            this.txtSupName.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtSupName.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtSupName.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtSupName.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtSupName.BorderRadius = 5;
            this.txtSupName.BorderThickness = 1;
            this.txtSupName.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtSupName.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtSupName.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSupName.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtSupName.DefaultText = "";
            this.txtSupName.FillColor = System.Drawing.Color.Gainsboro;
            this.txtSupName.HideSelection = true;
            this.txtSupName.IconLeft = null;
            this.txtSupName.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSupName.IconPadding = 10;
            this.txtSupName.IconRight = null;
            this.txtSupName.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSupName.Lines = new string[0];
            this.txtSupName.Location = new System.Drawing.Point(31, 187);
            this.txtSupName.MaxLength = 32767;
            this.txtSupName.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtSupName.Modified = false;
            this.txtSupName.Multiline = false;
            this.txtSupName.Name = "txtSupName";
            stateProperties21.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSupName.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtSupName.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSupName.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Silver;
            stateProperties24.FillColor = System.Drawing.Color.Gainsboro;
            stateProperties24.ForeColor = System.Drawing.Color.Empty;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSupName.OnIdleState = stateProperties24;
            this.txtSupName.Padding = new System.Windows.Forms.Padding(3);
            this.txtSupName.PasswordChar = '\0';
            this.txtSupName.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.txtSupName.PlaceholderText = "Supplier Name";
            this.txtSupName.ReadOnly = false;
            this.txtSupName.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtSupName.SelectedText = "";
            this.txtSupName.SelectionLength = 0;
            this.txtSupName.SelectionStart = 0;
            this.txtSupName.ShortcutsEnabled = true;
            this.txtSupName.Size = new System.Drawing.Size(300, 32);
            this.txtSupName.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtSupName.TabIndex = 32;
            this.txtSupName.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtSupName.TextMarginBottom = 0;
            this.txtSupName.TextMarginLeft = 3;
            this.txtSupName.TextMarginTop = 1;
            this.txtSupName.TextPlaceholder = "Supplier Name";
            this.txtSupName.UseSystemPasswordChar = false;
            this.txtSupName.WordWrap = true;
            // 
            // AddEditProdForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(665, 629);
            this.Controls.Add(this.pnlDialog);
            this.Name = "AddEditProdForm";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "AddEditProdForm";
            this.pnlDialog.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnSearch;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton1;
        public Bunifu.UI.WinForms.BunifuButton.BunifuButton btnAddEdit;
        private System.Windows.Forms.Label label1;
        public Bunifu.UI.WinForms.BunifuTextBox txtSupID;
        public System.Windows.Forms.Label lblTitle;
        private System.Windows.Forms.Label lblName;
        public Bunifu.UI.WinForms.BunifuTextBox txtName;
        private System.Windows.Forms.Label lblDepartment;
        public Bunifu.UI.WinForms.BunifuTextBox txtCategory;
        private System.Windows.Forms.Label lblDesc;
        public Bunifu.UI.WinForms.BunifuTextBox txtDesc;
        private System.Windows.Forms.Label lblSalary;
        public Bunifu.UI.WinForms.BunifuTextBox txtPurPrice;
        private Bunifu.UI.WinForms.BunifuPanel pnlDialog;
        private System.Windows.Forms.Label label2;
        public Bunifu.UI.WinForms.BunifuTextBox txtSku;
        private System.Windows.Forms.Label label3;
        public Bunifu.UI.WinForms.BunifuTextBox txtSalePrice;
        private System.Windows.Forms.Label label4;
        public Bunifu.UI.WinForms.BunifuTextBox txtThres;
        private System.Windows.Forms.Label label5;
        public Bunifu.UI.WinForms.BunifuTextBox txtStock;
        private System.Windows.Forms.Label label6;
        public Bunifu.UI.WinForms.BunifuTextBox txtSupName;
    }
}