namespace ERP_System.GUI.Components
{
    partial class AddEditEmpForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(AddEditEmpForm));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.pnlDialog = new Bunifu.UI.WinForms.BunifuPanel();
            this.btnSearch = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuButton1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnAddEdit = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.ddlStatus = new Bunifu.UI.WinForms.BunifuDropdown();
            this.label1 = new System.Windows.Forms.Label();
            this.txtUserID = new Bunifu.UI.WinForms.BunifuTextBox();
            this.lblTitle = new System.Windows.Forms.Label();
            this.lblName = new System.Windows.Forms.Label();
            this.txtName = new Bunifu.UI.WinForms.BunifuTextBox();
            this.lblDepartment = new System.Windows.Forms.Label();
            this.txtDepartment = new Bunifu.UI.WinForms.BunifuTextBox();
            this.lblRoleTitle = new System.Windows.Forms.Label();
            this.txtRoleTitle = new Bunifu.UI.WinForms.BunifuTextBox();
            this.lblSalary = new System.Windows.Forms.Label();
            this.txtSalary = new Bunifu.UI.WinForms.BunifuTextBox();
            this.lblStatus = new System.Windows.Forms.Label();
            this.pnlDialog.SuspendLayout();
            this.SuspendLayout();
            // 
            // pnlDialog
            // 
            this.pnlDialog.BackgroundColor = System.Drawing.Color.White;
            this.pnlDialog.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("pnlDialog.BackgroundImage")));
            this.pnlDialog.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.pnlDialog.BorderColor = System.Drawing.Color.LightGray;
            this.pnlDialog.BorderRadius = 20;
            this.pnlDialog.BorderThickness = 1;
            this.pnlDialog.Controls.Add(this.btnSearch);
            this.pnlDialog.Controls.Add(this.bunifuButton1);
            this.pnlDialog.Controls.Add(this.btnAddEdit);
            this.pnlDialog.Controls.Add(this.ddlStatus);
            this.pnlDialog.Controls.Add(this.label1);
            this.pnlDialog.Controls.Add(this.txtUserID);
            this.pnlDialog.Controls.Add(this.lblTitle);
            this.pnlDialog.Controls.Add(this.lblName);
            this.pnlDialog.Controls.Add(this.txtName);
            this.pnlDialog.Controls.Add(this.lblDepartment);
            this.pnlDialog.Controls.Add(this.txtDepartment);
            this.pnlDialog.Controls.Add(this.lblRoleTitle);
            this.pnlDialog.Controls.Add(this.txtRoleTitle);
            this.pnlDialog.Controls.Add(this.lblSalary);
            this.pnlDialog.Controls.Add(this.txtSalary);
            this.pnlDialog.Controls.Add(this.lblStatus);
            this.pnlDialog.Dock = System.Windows.Forms.DockStyle.Fill;
            this.pnlDialog.Location = new System.Drawing.Point(0, 0);
            this.pnlDialog.Name = "pnlDialog";
            this.pnlDialog.ShowBorders = true;
            this.pnlDialog.Size = new System.Drawing.Size(611, 583);
            this.pnlDialog.TabIndex = 0;
            // 
            // btnSearch
            // 
            this.btnSearch.AllowAnimations = true;
            this.btnSearch.AllowMouseEffects = true;
            this.btnSearch.AllowToggling = false;
            this.btnSearch.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btnSearch.AnimationSpeed = 200;
            this.btnSearch.AutoGenerateColors = false;
            this.btnSearch.AutoRoundBorders = false;
            this.btnSearch.AutoSizeLeftIcon = true;
            this.btnSearch.AutoSizeRightIcon = true;
            this.btnSearch.BackColor = System.Drawing.Color.Transparent;
            this.btnSearch.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(120)))), ((int)(((byte)(215)))));
            this.btnSearch.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnSearch.BackgroundImage")));
            this.btnSearch.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSearch.ButtonText = "Search";
            this.btnSearch.ButtonTextMarginLeft = 0;
            this.btnSearch.ColorContrastOnClick = 45;
            this.btnSearch.ColorContrastOnHover = 45;
            this.btnSearch.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnSearch.CustomizableEdges = borderEdges1;
            this.btnSearch.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnSearch.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSearch.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnSearch.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnSearch.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnSearch.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Bold);
            this.btnSearch.ForeColor = System.Drawing.Color.White;
            this.btnSearch.IconLeft = null;
            this.btnSearch.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnSearch.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnSearch.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnSearch.IconMarginLeft = 11;
            this.btnSearch.IconPadding = 10;
            this.btnSearch.IconRight = null;
            this.btnSearch.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnSearch.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnSearch.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnSearch.IconSize = 25;
            this.btnSearch.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(120)))), ((int)(((byte)(215)))));
            this.btnSearch.IdleBorderRadius = 6;
            this.btnSearch.IdleBorderThickness = 1;
            this.btnSearch.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(120)))), ((int)(((byte)(215)))));
            this.btnSearch.IdleIconLeftImage = null;
            this.btnSearch.IdleIconRightImage = null;
            this.btnSearch.IndicateFocus = false;
            this.btnSearch.Location = new System.Drawing.Point(287, 116);
            this.btnSearch.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.btnSearch.Name = "btnSearch";
            this.btnSearch.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSearch.OnDisabledState.BorderRadius = 15;
            this.btnSearch.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSearch.OnDisabledState.BorderThickness = 1;
            this.btnSearch.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSearch.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSearch.OnDisabledState.IconLeftImage = null;
            this.btnSearch.OnDisabledState.IconRightImage = null;
            this.btnSearch.onHoverState.BorderColor = System.Drawing.Color.Transparent;
            this.btnSearch.onHoverState.BorderRadius = 15;
            this.btnSearch.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSearch.onHoverState.BorderThickness = 1;
            this.btnSearch.onHoverState.FillColor = System.Drawing.Color.DimGray;
            this.btnSearch.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnSearch.onHoverState.IconLeftImage = null;
            this.btnSearch.onHoverState.IconRightImage = null;
            this.btnSearch.OnIdleState.BorderColor = System.Drawing.Color.Black;
            this.btnSearch.OnIdleState.BorderRadius = 15;
            this.btnSearch.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSearch.OnIdleState.BorderThickness = 1;
            this.btnSearch.OnIdleState.FillColor = System.Drawing.Color.Black;
            this.btnSearch.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnSearch.OnIdleState.IconLeftImage = null;
            this.btnSearch.OnIdleState.IconRightImage = null;
            this.btnSearch.OnPressedState.BorderColor = System.Drawing.Color.Transparent;
            this.btnSearch.OnPressedState.BorderRadius = 15;
            this.btnSearch.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSearch.OnPressedState.BorderThickness = 1;
            this.btnSearch.OnPressedState.FillColor = System.Drawing.Color.Black;
            this.btnSearch.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnSearch.OnPressedState.IconLeftImage = null;
            this.btnSearch.OnPressedState.IconRightImage = null;
            this.btnSearch.Size = new System.Drawing.Size(106, 32);
            this.btnSearch.TabIndex = 22;
            this.btnSearch.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnSearch.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnSearch.TextMarginLeft = 0;
            this.btnSearch.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnSearch.UseDefaultRadiusAndThickness = true;
            this.btnSearch.Click += new System.EventHandler(this.SearchEmployee_Click);
            // 
            // bunifuButton1
            // 
            this.bunifuButton1.AllowAnimations = true;
            this.bunifuButton1.AllowMouseEffects = true;
            this.bunifuButton1.AllowToggling = false;
            this.bunifuButton1.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.bunifuButton1.AnimationSpeed = 200;
            this.bunifuButton1.AutoGenerateColors = false;
            this.bunifuButton1.AutoRoundBorders = false;
            this.bunifuButton1.AutoSizeLeftIcon = true;
            this.bunifuButton1.AutoSizeRightIcon = true;
            this.bunifuButton1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton1.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(120)))), ((int)(((byte)(215)))));
            this.bunifuButton1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton1.BackgroundImage")));
            this.bunifuButton1.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.ButtonText = "Cancel";
            this.bunifuButton1.ButtonTextMarginLeft = 0;
            this.bunifuButton1.ColorContrastOnClick = 45;
            this.bunifuButton1.ColorContrastOnHover = 45;
            this.bunifuButton1.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.bunifuButton1.CustomizableEdges = borderEdges2;
            this.bunifuButton1.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton1.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton1.DisabledFillColor = System.Drawing.Color.Empty;
            this.bunifuButton1.DisabledForecolor = System.Drawing.Color.Empty;
            this.bunifuButton1.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButton1.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Bold);
            this.bunifuButton1.ForeColor = System.Drawing.Color.Black;
            this.bunifuButton1.IconLeft = null;
            this.bunifuButton1.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton1.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.bunifuButton1.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton1.IconMarginLeft = 11;
            this.bunifuButton1.IconPadding = 10;
            this.bunifuButton1.IconRight = null;
            this.bunifuButton1.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton1.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.bunifuButton1.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton1.IconSize = 25;
            this.bunifuButton1.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(120)))), ((int)(((byte)(215)))));
            this.bunifuButton1.IdleBorderRadius = 6;
            this.bunifuButton1.IdleBorderThickness = 1;
            this.bunifuButton1.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(120)))), ((int)(((byte)(215)))));
            this.bunifuButton1.IdleIconLeftImage = null;
            this.bunifuButton1.IdleIconRightImage = null;
            this.bunifuButton1.IndicateFocus = false;
            this.bunifuButton1.Location = new System.Drawing.Point(287, 516);
            this.bunifuButton1.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.bunifuButton1.Name = "bunifuButton1";
            this.bunifuButton1.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton1.OnDisabledState.BorderRadius = 15;
            this.bunifuButton1.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnDisabledState.BorderThickness = 2;
            this.bunifuButton1.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton1.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton1.OnDisabledState.IconLeftImage = null;
            this.bunifuButton1.OnDisabledState.IconRightImage = null;
            this.bunifuButton1.onHoverState.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuButton1.onHoverState.BorderRadius = 15;
            this.bunifuButton1.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.onHoverState.BorderThickness = 2;
            this.bunifuButton1.onHoverState.FillColor = System.Drawing.Color.DimGray;
            this.bunifuButton1.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.onHoverState.IconLeftImage = null;
            this.bunifuButton1.onHoverState.IconRightImage = null;
            this.bunifuButton1.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.bunifuButton1.OnIdleState.BorderRadius = 15;
            this.bunifuButton1.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnIdleState.BorderThickness = 2;
            this.bunifuButton1.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.bunifuButton1.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.bunifuButton1.OnIdleState.IconLeftImage = null;
            this.bunifuButton1.OnIdleState.IconRightImage = null;
            this.bunifuButton1.OnPressedState.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuButton1.OnPressedState.BorderRadius = 15;
            this.bunifuButton1.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnPressedState.BorderThickness = 2;
            this.bunifuButton1.OnPressedState.FillColor = System.Drawing.Color.Black;
            this.bunifuButton1.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.OnPressedState.IconLeftImage = null;
            this.bunifuButton1.OnPressedState.IconRightImage = null;
            this.bunifuButton1.Size = new System.Drawing.Size(149, 41);
            this.bunifuButton1.TabIndex = 19;
            this.bunifuButton1.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton1.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton1.TextMarginLeft = 0;
            this.bunifuButton1.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton1.UseDefaultRadiusAndThickness = true;
            this.bunifuButton1.Click += new System.EventHandler(this.bunifuButton1_Click);
            // 
            // btnAddEdit
            // 
            this.btnAddEdit.AllowAnimations = true;
            this.btnAddEdit.AllowMouseEffects = true;
            this.btnAddEdit.AllowToggling = false;
            this.btnAddEdit.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btnAddEdit.AnimationSpeed = 200;
            this.btnAddEdit.AutoGenerateColors = false;
            this.btnAddEdit.AutoRoundBorders = false;
            this.btnAddEdit.AutoSizeLeftIcon = true;
            this.btnAddEdit.AutoSizeRightIcon = true;
            this.btnAddEdit.BackColor = System.Drawing.Color.Transparent;
            this.btnAddEdit.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(120)))), ((int)(((byte)(215)))));
            this.btnAddEdit.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnAddEdit.BackgroundImage")));
            this.btnAddEdit.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAddEdit.ButtonText = "Add Employee";
            this.btnAddEdit.ButtonTextMarginLeft = 0;
            this.btnAddEdit.ColorContrastOnClick = 45;
            this.btnAddEdit.ColorContrastOnHover = 45;
            this.btnAddEdit.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btnAddEdit.CustomizableEdges = borderEdges3;
            this.btnAddEdit.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnAddEdit.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnAddEdit.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnAddEdit.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnAddEdit.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnAddEdit.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Bold);
            this.btnAddEdit.ForeColor = System.Drawing.Color.White;
            this.btnAddEdit.IconLeft = null;
            this.btnAddEdit.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnAddEdit.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnAddEdit.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnAddEdit.IconMarginLeft = 11;
            this.btnAddEdit.IconPadding = 10;
            this.btnAddEdit.IconRight = null;
            this.btnAddEdit.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnAddEdit.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnAddEdit.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnAddEdit.IconSize = 25;
            this.btnAddEdit.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(120)))), ((int)(((byte)(215)))));
            this.btnAddEdit.IdleBorderRadius = 6;
            this.btnAddEdit.IdleBorderThickness = 1;
            this.btnAddEdit.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(120)))), ((int)(((byte)(215)))));
            this.btnAddEdit.IdleIconLeftImage = null;
            this.btnAddEdit.IdleIconRightImage = null;
            this.btnAddEdit.IndicateFocus = false;
            this.btnAddEdit.Location = new System.Drawing.Point(442, 516);
            this.btnAddEdit.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.btnAddEdit.Name = "btnAddEdit";
            this.btnAddEdit.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnAddEdit.OnDisabledState.BorderRadius = 15;
            this.btnAddEdit.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAddEdit.OnDisabledState.BorderThickness = 1;
            this.btnAddEdit.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnAddEdit.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnAddEdit.OnDisabledState.IconLeftImage = null;
            this.btnAddEdit.OnDisabledState.IconRightImage = null;
            this.btnAddEdit.onHoverState.BorderColor = System.Drawing.Color.Transparent;
            this.btnAddEdit.onHoverState.BorderRadius = 15;
            this.btnAddEdit.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAddEdit.onHoverState.BorderThickness = 1;
            this.btnAddEdit.onHoverState.FillColor = System.Drawing.Color.DimGray;
            this.btnAddEdit.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnAddEdit.onHoverState.IconLeftImage = null;
            this.btnAddEdit.onHoverState.IconRightImage = null;
            this.btnAddEdit.OnIdleState.BorderColor = System.Drawing.Color.Black;
            this.btnAddEdit.OnIdleState.BorderRadius = 15;
            this.btnAddEdit.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAddEdit.OnIdleState.BorderThickness = 1;
            this.btnAddEdit.OnIdleState.FillColor = System.Drawing.Color.Black;
            this.btnAddEdit.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnAddEdit.OnIdleState.IconLeftImage = null;
            this.btnAddEdit.OnIdleState.IconRightImage = null;
            this.btnAddEdit.OnPressedState.BorderColor = System.Drawing.Color.Transparent;
            this.btnAddEdit.OnPressedState.BorderRadius = 15;
            this.btnAddEdit.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAddEdit.OnPressedState.BorderThickness = 1;
            this.btnAddEdit.OnPressedState.FillColor = System.Drawing.Color.Black;
            this.btnAddEdit.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnAddEdit.OnPressedState.IconLeftImage = null;
            this.btnAddEdit.OnPressedState.IconRightImage = null;
            this.btnAddEdit.Size = new System.Drawing.Size(149, 41);
            this.btnAddEdit.TabIndex = 18;
            this.btnAddEdit.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnAddEdit.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnAddEdit.TextMarginLeft = 0;
            this.btnAddEdit.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnAddEdit.UseDefaultRadiusAndThickness = true;
            this.btnAddEdit.Click += new System.EventHandler(this.AddEmployee_Click);
            // 
            // ddlStatus
            // 
            this.ddlStatus.BackColor = System.Drawing.Color.Gainsboro;
            this.ddlStatus.BackgroundColor = System.Drawing.Color.Gainsboro;
            this.ddlStatus.BorderColor = System.Drawing.Color.Gainsboro;
            this.ddlStatus.BorderRadius = 5;
            this.ddlStatus.Color = System.Drawing.Color.Gainsboro;
            this.ddlStatus.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.ddlStatus.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.ddlStatus.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.ddlStatus.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.ddlStatus.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.ddlStatus.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.ddlStatus.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.ddlStatus.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.ddlStatus.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.ddlStatus.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.ddlStatus.FillDropDown = true;
            this.ddlStatus.FillIndicator = false;
            this.ddlStatus.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.ddlStatus.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.ddlStatus.ForeColor = System.Drawing.Color.Black;
            this.ddlStatus.Icon = null;
            this.ddlStatus.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.ddlStatus.IndicatorColor = System.Drawing.Color.DarkGray;
            this.ddlStatus.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.ddlStatus.IndicatorThickness = 2;
            this.ddlStatus.IsDropdownOpened = false;
            this.ddlStatus.ItemBackColor = System.Drawing.Color.White;
            this.ddlStatus.ItemBorderColor = System.Drawing.Color.White;
            this.ddlStatus.ItemForeColor = System.Drawing.Color.Black;
            this.ddlStatus.ItemHeight = 26;
            this.ddlStatus.ItemHighLightColor = System.Drawing.Color.DodgerBlue;
            this.ddlStatus.ItemHighLightForeColor = System.Drawing.Color.White;
            this.ddlStatus.Items.AddRange(new object[] {
            "active",
            "inactive"});
            this.ddlStatus.ItemTopMargin = 3;
            this.ddlStatus.Location = new System.Drawing.Point(231, 442);
            this.ddlStatus.Name = "ddlStatus";
            this.ddlStatus.Size = new System.Drawing.Size(200, 32);
            this.ddlStatus.TabIndex = 17;
            this.ddlStatus.Text = null;
            this.ddlStatus.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.ddlStatus.TextLeftMargin = 5;
            // 
            // label1
            // 
            this.label1.BackColor = System.Drawing.Color.Transparent;
            this.label1.Font = new System.Drawing.Font("Segoe UI", 10.944F, System.Drawing.FontStyle.Bold);
            this.label1.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(50)))), ((int)(((byte)(58)))));
            this.label1.Location = new System.Drawing.Point(30, 90);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(131, 23);
            this.label1.TabIndex = 14;
            this.label1.Text = "User ID";
            // 
            // txtUserID
            // 
            this.txtUserID.AcceptsReturn = false;
            this.txtUserID.AcceptsTab = false;
            this.txtUserID.AnimationSpeed = 200;
            this.txtUserID.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtUserID.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtUserID.AutoSizeHeight = true;
            this.txtUserID.BackColor = System.Drawing.Color.Transparent;
            this.txtUserID.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtUserID.BackgroundImage")));
            this.txtUserID.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtUserID.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtUserID.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtUserID.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtUserID.BorderRadius = 5;
            this.txtUserID.BorderThickness = 1;
            this.txtUserID.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtUserID.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtUserID.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtUserID.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtUserID.DefaultText = "";
            this.txtUserID.FillColor = System.Drawing.Color.Gainsboro;
            this.txtUserID.HideSelection = true;
            this.txtUserID.IconLeft = null;
            this.txtUserID.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtUserID.IconPadding = 10;
            this.txtUserID.IconRight = null;
            this.txtUserID.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtUserID.Lines = new string[0];
            this.txtUserID.Location = new System.Drawing.Point(35, 116);
            this.txtUserID.MaxLength = 32767;
            this.txtUserID.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtUserID.Modified = false;
            this.txtUserID.Multiline = false;
            this.txtUserID.Name = "txtUserID";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtUserID.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtUserID.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtUserID.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.Gainsboro;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtUserID.OnIdleState = stateProperties4;
            this.txtUserID.Padding = new System.Windows.Forms.Padding(3);
            this.txtUserID.PasswordChar = '\0';
            this.txtUserID.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.txtUserID.PlaceholderText = "Enter User ID";
            this.txtUserID.ReadOnly = false;
            this.txtUserID.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtUserID.SelectedText = "";
            this.txtUserID.SelectionLength = 0;
            this.txtUserID.SelectionStart = 0;
            this.txtUserID.ShortcutsEnabled = true;
            this.txtUserID.Size = new System.Drawing.Size(234, 32);
            this.txtUserID.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtUserID.TabIndex = 13;
            this.txtUserID.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtUserID.TextMarginBottom = 0;
            this.txtUserID.TextMarginLeft = 3;
            this.txtUserID.TextMarginTop = 1;
            this.txtUserID.TextPlaceholder = "Enter User ID";
            this.txtUserID.UseSystemPasswordChar = false;
            this.txtUserID.WordWrap = true;
            // 
            // lblTitle
            // 
            this.lblTitle.BackColor = System.Drawing.Color.Transparent;
            this.lblTitle.Font = new System.Drawing.Font("Segoe UI Semibold", 14F, System.Drawing.FontStyle.Bold);
            this.lblTitle.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(50)))), ((int)(((byte)(58)))));
            this.lblTitle.Location = new System.Drawing.Point(225, 9);
            this.lblTitle.Name = "lblTitle";
            this.lblTitle.Size = new System.Drawing.Size(186, 33);
            this.lblTitle.TabIndex = 0;
            this.lblTitle.Text = "Add Employee";
            // 
            // lblName
            // 
            this.lblName.BackColor = System.Drawing.Color.Transparent;
            this.lblName.Font = new System.Drawing.Font("Segoe UI", 10.944F, System.Drawing.FontStyle.Bold);
            this.lblName.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(50)))), ((int)(((byte)(58)))));
            this.lblName.Location = new System.Drawing.Point(30, 167);
            this.lblName.Name = "lblName";
            this.lblName.Size = new System.Drawing.Size(110, 23);
            this.lblName.TabIndex = 1;
            this.lblName.Text = " Name";
            // 
            // txtName
            // 
            this.txtName.AcceptsReturn = false;
            this.txtName.AcceptsTab = false;
            this.txtName.AnimationSpeed = 200;
            this.txtName.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtName.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtName.AutoSizeHeight = true;
            this.txtName.BackColor = System.Drawing.Color.Transparent;
            this.txtName.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtName.BackgroundImage")));
            this.txtName.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtName.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtName.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtName.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtName.BorderRadius = 5;
            this.txtName.BorderThickness = 1;
            this.txtName.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtName.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtName.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtName.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtName.DefaultText = "";
            this.txtName.FillColor = System.Drawing.Color.Gainsboro;
            this.txtName.HideSelection = true;
            this.txtName.IconLeft = null;
            this.txtName.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtName.IconPadding = 10;
            this.txtName.IconRight = null;
            this.txtName.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtName.Lines = new string[0];
            this.txtName.Location = new System.Drawing.Point(35, 193);
            this.txtName.MaxLength = 32767;
            this.txtName.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtName.Modified = false;
            this.txtName.Multiline = false;
            this.txtName.Name = "txtName";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtName.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtName.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtName.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.Gainsboro;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtName.OnIdleState = stateProperties8;
            this.txtName.Padding = new System.Windows.Forms.Padding(3);
            this.txtName.PasswordChar = '\0';
            this.txtName.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.txtName.PlaceholderText = "Enter full name";
            this.txtName.ReadOnly = false;
            this.txtName.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtName.SelectedText = "";
            this.txtName.SelectionLength = 0;
            this.txtName.SelectionStart = 0;
            this.txtName.ShortcutsEnabled = true;
            this.txtName.Size = new System.Drawing.Size(300, 32);
            this.txtName.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtName.TabIndex = 2;
            this.txtName.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtName.TextMarginBottom = 0;
            this.txtName.TextMarginLeft = 3;
            this.txtName.TextMarginTop = 1;
            this.txtName.TextPlaceholder = "Enter full name";
            this.txtName.UseSystemPasswordChar = false;
            this.txtName.WordWrap = true;
            // 
            // lblDepartment
            // 
            this.lblDepartment.BackColor = System.Drawing.Color.Transparent;
            this.lblDepartment.Font = new System.Drawing.Font("Segoe UI", 10.944F, System.Drawing.FontStyle.Bold);
            this.lblDepartment.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(50)))), ((int)(((byte)(58)))));
            this.lblDepartment.Location = new System.Drawing.Point(30, 242);
            this.lblDepartment.Name = "lblDepartment";
            this.lblDepartment.Size = new System.Drawing.Size(131, 23);
            this.lblDepartment.TabIndex = 3;
            this.lblDepartment.Text = "Department";
            // 
            // txtDepartment
            // 
            this.txtDepartment.AcceptsReturn = false;
            this.txtDepartment.AcceptsTab = false;
            this.txtDepartment.AnimationSpeed = 200;
            this.txtDepartment.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtDepartment.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtDepartment.AutoSizeHeight = true;
            this.txtDepartment.BackColor = System.Drawing.Color.Transparent;
            this.txtDepartment.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtDepartment.BackgroundImage")));
            this.txtDepartment.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtDepartment.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtDepartment.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtDepartment.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtDepartment.BorderRadius = 5;
            this.txtDepartment.BorderThickness = 1;
            this.txtDepartment.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtDepartment.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtDepartment.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDepartment.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtDepartment.DefaultText = "";
            this.txtDepartment.FillColor = System.Drawing.Color.Gainsboro;
            this.txtDepartment.HideSelection = true;
            this.txtDepartment.IconLeft = null;
            this.txtDepartment.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDepartment.IconPadding = 10;
            this.txtDepartment.IconRight = null;
            this.txtDepartment.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDepartment.Lines = new string[0];
            this.txtDepartment.Location = new System.Drawing.Point(35, 275);
            this.txtDepartment.MaxLength = 32767;
            this.txtDepartment.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtDepartment.Modified = false;
            this.txtDepartment.Multiline = false;
            this.txtDepartment.Name = "txtDepartment";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDepartment.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtDepartment.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDepartment.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.Gainsboro;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDepartment.OnIdleState = stateProperties12;
            this.txtDepartment.Padding = new System.Windows.Forms.Padding(3);
            this.txtDepartment.PasswordChar = '\0';
            this.txtDepartment.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.txtDepartment.PlaceholderText = "Enter Department";
            this.txtDepartment.ReadOnly = false;
            this.txtDepartment.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtDepartment.SelectedText = "";
            this.txtDepartment.SelectionLength = 0;
            this.txtDepartment.SelectionStart = 0;
            this.txtDepartment.ShortcutsEnabled = true;
            this.txtDepartment.Size = new System.Drawing.Size(300, 32);
            this.txtDepartment.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtDepartment.TabIndex = 4;
            this.txtDepartment.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtDepartment.TextMarginBottom = 0;
            this.txtDepartment.TextMarginLeft = 3;
            this.txtDepartment.TextMarginTop = 1;
            this.txtDepartment.TextPlaceholder = "Enter Department";
            this.txtDepartment.UseSystemPasswordChar = false;
            this.txtDepartment.WordWrap = true;
            // 
            // lblRoleTitle
            // 
            this.lblRoleTitle.BackColor = System.Drawing.Color.Transparent;
            this.lblRoleTitle.Font = new System.Drawing.Font("Segoe UI", 10.944F, System.Drawing.FontStyle.Bold);
            this.lblRoleTitle.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(50)))), ((int)(((byte)(58)))));
            this.lblRoleTitle.Location = new System.Drawing.Point(30, 324);
            this.lblRoleTitle.Name = "lblRoleTitle";
            this.lblRoleTitle.Size = new System.Drawing.Size(100, 23);
            this.lblRoleTitle.TabIndex = 5;
            this.lblRoleTitle.Text = "Job Title";
            // 
            // txtRoleTitle
            // 
            this.txtRoleTitle.AcceptsReturn = false;
            this.txtRoleTitle.AcceptsTab = false;
            this.txtRoleTitle.AnimationSpeed = 200;
            this.txtRoleTitle.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtRoleTitle.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtRoleTitle.AutoSizeHeight = true;
            this.txtRoleTitle.BackColor = System.Drawing.Color.Transparent;
            this.txtRoleTitle.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtRoleTitle.BackgroundImage")));
            this.txtRoleTitle.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtRoleTitle.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtRoleTitle.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtRoleTitle.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtRoleTitle.BorderRadius = 5;
            this.txtRoleTitle.BorderThickness = 1;
            this.txtRoleTitle.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtRoleTitle.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtRoleTitle.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtRoleTitle.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtRoleTitle.DefaultText = "";
            this.txtRoleTitle.FillColor = System.Drawing.Color.Gainsboro;
            this.txtRoleTitle.HideSelection = true;
            this.txtRoleTitle.IconLeft = null;
            this.txtRoleTitle.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtRoleTitle.IconPadding = 10;
            this.txtRoleTitle.IconRight = null;
            this.txtRoleTitle.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtRoleTitle.Lines = new string[0];
            this.txtRoleTitle.Location = new System.Drawing.Point(35, 360);
            this.txtRoleTitle.MaxLength = 32767;
            this.txtRoleTitle.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtRoleTitle.Modified = false;
            this.txtRoleTitle.Multiline = false;
            this.txtRoleTitle.Name = "txtRoleTitle";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtRoleTitle.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtRoleTitle.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtRoleTitle.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.Gainsboro;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtRoleTitle.OnIdleState = stateProperties16;
            this.txtRoleTitle.Padding = new System.Windows.Forms.Padding(3);
            this.txtRoleTitle.PasswordChar = '\0';
            this.txtRoleTitle.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.txtRoleTitle.PlaceholderText = "Enter  Job title";
            this.txtRoleTitle.ReadOnly = false;
            this.txtRoleTitle.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtRoleTitle.SelectedText = "";
            this.txtRoleTitle.SelectionLength = 0;
            this.txtRoleTitle.SelectionStart = 0;
            this.txtRoleTitle.ShortcutsEnabled = true;
            this.txtRoleTitle.Size = new System.Drawing.Size(300, 32);
            this.txtRoleTitle.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtRoleTitle.TabIndex = 6;
            this.txtRoleTitle.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtRoleTitle.TextMarginBottom = 0;
            this.txtRoleTitle.TextMarginLeft = 3;
            this.txtRoleTitle.TextMarginTop = 1;
            this.txtRoleTitle.TextPlaceholder = "Enter  Job title";
            this.txtRoleTitle.UseSystemPasswordChar = false;
            this.txtRoleTitle.WordWrap = true;
            // 
            // lblSalary
            // 
            this.lblSalary.BackColor = System.Drawing.Color.Transparent;
            this.lblSalary.Font = new System.Drawing.Font("Segoe UI", 10.944F, System.Drawing.FontStyle.Bold);
            this.lblSalary.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(50)))), ((int)(((byte)(58)))));
            this.lblSalary.Location = new System.Drawing.Point(30, 407);
            this.lblSalary.Name = "lblSalary";
            this.lblSalary.Size = new System.Drawing.Size(100, 23);
            this.lblSalary.TabIndex = 7;
            this.lblSalary.Text = "Salary";
            // 
            // txtSalary
            // 
            this.txtSalary.AcceptsReturn = false;
            this.txtSalary.AcceptsTab = false;
            this.txtSalary.AnimationSpeed = 200;
            this.txtSalary.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtSalary.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtSalary.AutoSizeHeight = true;
            this.txtSalary.BackColor = System.Drawing.Color.Transparent;
            this.txtSalary.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtSalary.BackgroundImage")));
            this.txtSalary.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtSalary.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtSalary.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtSalary.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtSalary.BorderRadius = 5;
            this.txtSalary.BorderThickness = 1;
            this.txtSalary.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtSalary.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtSalary.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSalary.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtSalary.DefaultText = "";
            this.txtSalary.FillColor = System.Drawing.Color.Gainsboro;
            this.txtSalary.HideSelection = true;
            this.txtSalary.IconLeft = null;
            this.txtSalary.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSalary.IconPadding = 10;
            this.txtSalary.IconRight = null;
            this.txtSalary.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSalary.Lines = new string[0];
            this.txtSalary.Location = new System.Drawing.Point(35, 442);
            this.txtSalary.MaxLength = 32767;
            this.txtSalary.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtSalary.Modified = false;
            this.txtSalary.Multiline = false;
            this.txtSalary.Name = "txtSalary";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSalary.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtSalary.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSalary.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.Gainsboro;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSalary.OnIdleState = stateProperties20;
            this.txtSalary.Padding = new System.Windows.Forms.Padding(3);
            this.txtSalary.PasswordChar = '\0';
            this.txtSalary.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.txtSalary.PlaceholderText = "Numeric Salary";
            this.txtSalary.ReadOnly = false;
            this.txtSalary.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtSalary.SelectedText = "";
            this.txtSalary.SelectionLength = 0;
            this.txtSalary.SelectionStart = 0;
            this.txtSalary.ShortcutsEnabled = true;
            this.txtSalary.Size = new System.Drawing.Size(175, 32);
            this.txtSalary.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtSalary.TabIndex = 8;
            this.txtSalary.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtSalary.TextMarginBottom = 0;
            this.txtSalary.TextMarginLeft = 3;
            this.txtSalary.TextMarginTop = 1;
            this.txtSalary.TextPlaceholder = "Numeric Salary";
            this.txtSalary.UseSystemPasswordChar = false;
            this.txtSalary.WordWrap = true;
            // 
            // lblStatus
            // 
            this.lblStatus.BackColor = System.Drawing.Color.White;
            this.lblStatus.Font = new System.Drawing.Font("Segoe UI", 10.944F, System.Drawing.FontStyle.Bold);
            this.lblStatus.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(50)))), ((int)(((byte)(58)))));
            this.lblStatus.Location = new System.Drawing.Point(235, 407);
            this.lblStatus.Name = "lblStatus";
            this.lblStatus.Size = new System.Drawing.Size(100, 23);
            this.lblStatus.TabIndex = 9;
            this.lblStatus.Text = "Status";
            // 
            // AddEditEmpForm
            // 
            this.ClientSize = new System.Drawing.Size(611, 583);
            this.Controls.Add(this.pnlDialog);
            this.Name = "AddEditEmpForm";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.pnlDialog.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        private System.Windows.Forms.Label lblStatus;
        private System.Windows.Forms.Label lblSalary;
        private System.Windows.Forms.Label lblRoleTitle;
        private System.Windows.Forms.Label lblDepartment;
        private System.Windows.Forms.Label lblName;
        private System.Windows.Forms.Label label1;
        private Bunifu.UI.WinForms.BunifuPanel pnlDialog;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnSearch;
        public System.Windows.Forms.Label lblTitle;
        public Bunifu.UI.WinForms.BunifuButton.BunifuButton btnAddEdit;
        public Bunifu.UI.WinForms.BunifuTextBox txtName;
        public Bunifu.UI.WinForms.BunifuTextBox txtUserID;
        public Bunifu.UI.WinForms.BunifuTextBox txtSalary;
        public Bunifu.UI.WinForms.BunifuTextBox txtRoleTitle;
        public Bunifu.UI.WinForms.BunifuTextBox txtDepartment;
        public Bunifu.UI.WinForms.BunifuDropdown ddlStatus;
    }

    #endregion
}