namespace ERP_System.GUI
{
    partial class SideNavBar
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(SideNavBar));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges8 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges9 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.bunifuPanel1 = new Bunifu.UI.WinForms.BunifuPanel();
            this.btnUserProfile = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuSeparator5 = new Bunifu.UI.WinForms.BunifuSeparator();
            this.bunifuSeparator4 = new Bunifu.UI.WinForms.BunifuSeparator();
            this.bunifuSeparator3 = new Bunifu.UI.WinForms.BunifuSeparator();
            this.bunifuSeparator2 = new Bunifu.UI.WinForms.BunifuSeparator();
            this.btnHistory = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnPurchases = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnSales = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuLabel6 = new Bunifu.UI.WinForms.BunifuLabel();
            this.btnStkAdj = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnSup = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnProd = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuLabel5 = new Bunifu.UI.WinForms.BunifuLabel();
            this.btnEmp = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuLabel4 = new Bunifu.UI.WinForms.BunifuLabel();
            this.btnDashboard = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuSeparator1 = new Bunifu.UI.WinForms.BunifuSeparator();
            this.bunifuLabel3 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuPanel1.SuspendLayout();
            this.SuspendLayout();
            // 
            // bunifuPanel1
            // 
            this.bunifuPanel1.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(64)))));
            this.bunifuPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel1.BackgroundImage")));
            this.bunifuPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel1.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuPanel1.BorderRadius = 3;
            this.bunifuPanel1.BorderThickness = 1;
            this.bunifuPanel1.Controls.Add(this.bunifuLabel2);
            this.bunifuPanel1.Controls.Add(this.bunifuLabel1);
            this.bunifuPanel1.Controls.Add(this.btnUserProfile);
            this.bunifuPanel1.Controls.Add(this.bunifuSeparator5);
            this.bunifuPanel1.Controls.Add(this.bunifuSeparator4);
            this.bunifuPanel1.Controls.Add(this.bunifuSeparator3);
            this.bunifuPanel1.Controls.Add(this.bunifuSeparator2);
            this.bunifuPanel1.Controls.Add(this.btnHistory);
            this.bunifuPanel1.Controls.Add(this.btnPurchases);
            this.bunifuPanel1.Controls.Add(this.btnSales);
            this.bunifuPanel1.Controls.Add(this.bunifuLabel6);
            this.bunifuPanel1.Controls.Add(this.btnStkAdj);
            this.bunifuPanel1.Controls.Add(this.btnSup);
            this.bunifuPanel1.Controls.Add(this.btnProd);
            this.bunifuPanel1.Controls.Add(this.bunifuLabel5);
            this.bunifuPanel1.Controls.Add(this.btnEmp);
            this.bunifuPanel1.Controls.Add(this.bunifuLabel4);
            this.bunifuPanel1.Controls.Add(this.btnDashboard);
            this.bunifuPanel1.Controls.Add(this.bunifuSeparator1);
            this.bunifuPanel1.Controls.Add(this.bunifuLabel3);
            this.bunifuPanel1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.bunifuPanel1.Font = new System.Drawing.Font("Marlett", 8.25F);
            this.bunifuPanel1.Location = new System.Drawing.Point(0, 0);
            this.bunifuPanel1.Name = "bunifuPanel1";
            this.bunifuPanel1.ShowBorders = true;
            this.bunifuPanel1.Size = new System.Drawing.Size(305, 1032);
            this.bunifuPanel1.TabIndex = 0;
            // 
            // btnUserProfile
            // 
            this.btnUserProfile.AllowAnimations = true;
            this.btnUserProfile.AllowMouseEffects = true;
            this.btnUserProfile.AllowToggling = false;
            this.btnUserProfile.AnimationSpeed = 200;
            this.btnUserProfile.AutoGenerateColors = false;
            this.btnUserProfile.AutoRoundBorders = false;
            this.btnUserProfile.AutoSizeLeftIcon = true;
            this.btnUserProfile.AutoSizeRightIcon = true;
            this.btnUserProfile.BackColor = System.Drawing.Color.Transparent;
            this.btnUserProfile.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnUserProfile.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnUserProfile.BackgroundImage")));
            this.btnUserProfile.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnUserProfile.ButtonText = "User Profile";
            this.btnUserProfile.ButtonTextMarginLeft = 0;
            this.btnUserProfile.ColorContrastOnClick = 45;
            this.btnUserProfile.ColorContrastOnHover = 45;
            this.btnUserProfile.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnUserProfile.CustomizableEdges = borderEdges1;
            this.btnUserProfile.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnUserProfile.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnUserProfile.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnUserProfile.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnUserProfile.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnUserProfile.Font = new System.Drawing.Font("Segoe UI", 13.824F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnUserProfile.ForeColor = System.Drawing.Color.White;
            this.btnUserProfile.IconLeft = null;
            this.btnUserProfile.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnUserProfile.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnUserProfile.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnUserProfile.IconMarginLeft = 11;
            this.btnUserProfile.IconPadding = 10;
            this.btnUserProfile.IconRight = null;
            this.btnUserProfile.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnUserProfile.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnUserProfile.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnUserProfile.IconSize = 25;
            this.btnUserProfile.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnUserProfile.IdleBorderRadius = 0;
            this.btnUserProfile.IdleBorderThickness = 0;
            this.btnUserProfile.IdleFillColor = System.Drawing.Color.Empty;
            this.btnUserProfile.IdleIconLeftImage = null;
            this.btnUserProfile.IdleIconRightImage = null;
            this.btnUserProfile.IndicateFocus = false;
            this.btnUserProfile.Location = new System.Drawing.Point(19, 863);
            this.btnUserProfile.Name = "btnUserProfile";
            this.btnUserProfile.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnUserProfile.OnDisabledState.BorderRadius = 15;
            this.btnUserProfile.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnUserProfile.OnDisabledState.BorderThickness = 1;
            this.btnUserProfile.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnUserProfile.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnUserProfile.OnDisabledState.IconLeftImage = null;
            this.btnUserProfile.OnDisabledState.IconRightImage = null;
            this.btnUserProfile.onHoverState.BorderColor = System.Drawing.Color.Transparent;
            this.btnUserProfile.onHoverState.BorderRadius = 15;
            this.btnUserProfile.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnUserProfile.onHoverState.BorderThickness = 1;
            this.btnUserProfile.onHoverState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnUserProfile.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnUserProfile.onHoverState.IconLeftImage = null;
            this.btnUserProfile.onHoverState.IconRightImage = null;
            this.btnUserProfile.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btnUserProfile.OnIdleState.BorderRadius = 15;
            this.btnUserProfile.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnUserProfile.OnIdleState.BorderThickness = 1;
            this.btnUserProfile.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btnUserProfile.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnUserProfile.OnIdleState.IconLeftImage = null;
            this.btnUserProfile.OnIdleState.IconRightImage = null;
            this.btnUserProfile.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnUserProfile.OnPressedState.BorderRadius = 15;
            this.btnUserProfile.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnUserProfile.OnPressedState.BorderThickness = 1;
            this.btnUserProfile.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnUserProfile.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnUserProfile.OnPressedState.IconLeftImage = null;
            this.btnUserProfile.OnPressedState.IconRightImage = null;
            this.btnUserProfile.Size = new System.Drawing.Size(245, 47);
            this.btnUserProfile.TabIndex = 19;
            this.btnUserProfile.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnUserProfile.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnUserProfile.TextMarginLeft = 0;
            this.btnUserProfile.TextPadding = new System.Windows.Forms.Padding(15, 0, 0, 0);
            this.btnUserProfile.UseDefaultRadiusAndThickness = true;
            // 
            // bunifuSeparator5
            // 
            this.bunifuSeparator5.BackColor = System.Drawing.Color.Transparent;
            this.bunifuSeparator5.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuSeparator5.BackgroundImage")));
            this.bunifuSeparator5.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuSeparator5.DashCap = Bunifu.UI.WinForms.BunifuSeparator.CapStyles.Flat;
            this.bunifuSeparator5.LineColor = System.Drawing.Color.DarkGray;
            this.bunifuSeparator5.LineStyle = Bunifu.UI.WinForms.BunifuSeparator.LineStyles.Solid;
            this.bunifuSeparator5.LineThickness = 1;
            this.bunifuSeparator5.Location = new System.Drawing.Point(19, 834);
            this.bunifuSeparator5.Margin = new System.Windows.Forms.Padding(8, 4, 8, 4);
            this.bunifuSeparator5.Name = "bunifuSeparator5";
            this.bunifuSeparator5.Orientation = Bunifu.UI.WinForms.BunifuSeparator.LineOrientation.Horizontal;
            this.bunifuSeparator5.Size = new System.Drawing.Size(247, 13);
            this.bunifuSeparator5.TabIndex = 18;
            // 
            // bunifuSeparator4
            // 
            this.bunifuSeparator4.BackColor = System.Drawing.Color.Transparent;
            this.bunifuSeparator4.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuSeparator4.BackgroundImage")));
            this.bunifuSeparator4.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuSeparator4.DashCap = Bunifu.UI.WinForms.BunifuSeparator.CapStyles.Flat;
            this.bunifuSeparator4.LineColor = System.Drawing.Color.DarkGray;
            this.bunifuSeparator4.LineStyle = Bunifu.UI.WinForms.BunifuSeparator.LineStyles.Solid;
            this.bunifuSeparator4.LineThickness = 1;
            this.bunifuSeparator4.Location = new System.Drawing.Point(21, 605);
            this.bunifuSeparator4.Margin = new System.Windows.Forms.Padding(8, 4, 8, 4);
            this.bunifuSeparator4.Name = "bunifuSeparator4";
            this.bunifuSeparator4.Orientation = Bunifu.UI.WinForms.BunifuSeparator.LineOrientation.Horizontal;
            this.bunifuSeparator4.Size = new System.Drawing.Size(245, 13);
            this.bunifuSeparator4.TabIndex = 17;
            // 
            // bunifuSeparator3
            // 
            this.bunifuSeparator3.BackColor = System.Drawing.Color.Transparent;
            this.bunifuSeparator3.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuSeparator3.BackgroundImage")));
            this.bunifuSeparator3.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuSeparator3.DashCap = Bunifu.UI.WinForms.BunifuSeparator.CapStyles.Flat;
            this.bunifuSeparator3.LineColor = System.Drawing.Color.DarkGray;
            this.bunifuSeparator3.LineStyle = Bunifu.UI.WinForms.BunifuSeparator.LineStyles.Solid;
            this.bunifuSeparator3.LineThickness = 1;
            this.bunifuSeparator3.Location = new System.Drawing.Point(21, 363);
            this.bunifuSeparator3.Margin = new System.Windows.Forms.Padding(8, 4, 8, 4);
            this.bunifuSeparator3.Name = "bunifuSeparator3";
            this.bunifuSeparator3.Orientation = Bunifu.UI.WinForms.BunifuSeparator.LineOrientation.Horizontal;
            this.bunifuSeparator3.Size = new System.Drawing.Size(234, 10);
            this.bunifuSeparator3.TabIndex = 16;
            // 
            // bunifuSeparator2
            // 
            this.bunifuSeparator2.BackColor = System.Drawing.Color.Transparent;
            this.bunifuSeparator2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuSeparator2.BackgroundImage")));
            this.bunifuSeparator2.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuSeparator2.DashCap = Bunifu.UI.WinForms.BunifuSeparator.CapStyles.Flat;
            this.bunifuSeparator2.LineColor = System.Drawing.Color.DarkGray;
            this.bunifuSeparator2.LineStyle = Bunifu.UI.WinForms.BunifuSeparator.LineStyles.Solid;
            this.bunifuSeparator2.LineThickness = 1;
            this.bunifuSeparator2.Location = new System.Drawing.Point(19, 245);
            this.bunifuSeparator2.Margin = new System.Windows.Forms.Padding(6, 4, 6, 4);
            this.bunifuSeparator2.Name = "bunifuSeparator2";
            this.bunifuSeparator2.Orientation = Bunifu.UI.WinForms.BunifuSeparator.LineOrientation.Horizontal;
            this.bunifuSeparator2.Size = new System.Drawing.Size(235, 15);
            this.bunifuSeparator2.TabIndex = 15;
            // 
            // btnHistory
            // 
            this.btnHistory.AllowAnimations = true;
            this.btnHistory.AllowMouseEffects = true;
            this.btnHistory.AllowToggling = false;
            this.btnHistory.AnimationSpeed = 200;
            this.btnHistory.AutoGenerateColors = false;
            this.btnHistory.AutoRoundBorders = false;
            this.btnHistory.AutoSizeLeftIcon = true;
            this.btnHistory.AutoSizeRightIcon = true;
            this.btnHistory.BackColor = System.Drawing.Color.Transparent;
            this.btnHistory.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnHistory.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnHistory.BackgroundImage")));
            this.btnHistory.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnHistory.ButtonText = "Transaction History";
            this.btnHistory.ButtonTextMarginLeft = 0;
            this.btnHistory.ColorContrastOnClick = 45;
            this.btnHistory.ColorContrastOnHover = 45;
            this.btnHistory.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnHistory.CustomizableEdges = borderEdges2;
            this.btnHistory.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnHistory.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnHistory.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnHistory.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnHistory.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnHistory.Font = new System.Drawing.Font("Segoe UI Semibold", 9.792F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnHistory.ForeColor = System.Drawing.Color.White;
            this.btnHistory.IconLeft = null;
            this.btnHistory.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnHistory.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnHistory.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnHistory.IconMarginLeft = 11;
            this.btnHistory.IconPadding = 10;
            this.btnHistory.IconRight = null;
            this.btnHistory.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnHistory.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnHistory.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnHistory.IconSize = 25;
            this.btnHistory.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnHistory.IdleBorderRadius = 0;
            this.btnHistory.IdleBorderThickness = 0;
            this.btnHistory.IdleFillColor = System.Drawing.Color.Empty;
            this.btnHistory.IdleIconLeftImage = null;
            this.btnHistory.IdleIconRightImage = null;
            this.btnHistory.IndicateFocus = false;
            this.btnHistory.Location = new System.Drawing.Point(21, 774);
            this.btnHistory.Name = "btnHistory";
            this.btnHistory.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnHistory.OnDisabledState.BorderRadius = 15;
            this.btnHistory.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnHistory.OnDisabledState.BorderThickness = 1;
            this.btnHistory.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnHistory.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnHistory.OnDisabledState.IconLeftImage = null;
            this.btnHistory.OnDisabledState.IconRightImage = null;
            this.btnHistory.onHoverState.BorderColor = System.Drawing.Color.Transparent;
            this.btnHistory.onHoverState.BorderRadius = 15;
            this.btnHistory.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnHistory.onHoverState.BorderThickness = 1;
            this.btnHistory.onHoverState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnHistory.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnHistory.onHoverState.IconLeftImage = null;
            this.btnHistory.onHoverState.IconRightImage = null;
            this.btnHistory.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btnHistory.OnIdleState.BorderRadius = 15;
            this.btnHistory.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnHistory.OnIdleState.BorderThickness = 1;
            this.btnHistory.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btnHistory.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnHistory.OnIdleState.IconLeftImage = null;
            this.btnHistory.OnIdleState.IconRightImage = null;
            this.btnHistory.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnHistory.OnPressedState.BorderRadius = 15;
            this.btnHistory.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnHistory.OnPressedState.BorderThickness = 1;
            this.btnHistory.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnHistory.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnHistory.OnPressedState.IconLeftImage = null;
            this.btnHistory.OnPressedState.IconRightImage = null;
            this.btnHistory.Size = new System.Drawing.Size(235, 42);
            this.btnHistory.TabIndex = 14;
            this.btnHistory.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnHistory.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnHistory.TextMarginLeft = 0;
            this.btnHistory.TextPadding = new System.Windows.Forms.Padding(15, 0, 0, 0);
            this.btnHistory.UseDefaultRadiusAndThickness = true;
            // 
            // btnPurchases
            // 
            this.btnPurchases.AllowAnimations = true;
            this.btnPurchases.AllowMouseEffects = true;
            this.btnPurchases.AllowToggling = false;
            this.btnPurchases.AnimationSpeed = 200;
            this.btnPurchases.AutoGenerateColors = false;
            this.btnPurchases.AutoRoundBorders = false;
            this.btnPurchases.AutoSizeLeftIcon = true;
            this.btnPurchases.AutoSizeRightIcon = true;
            this.btnPurchases.BackColor = System.Drawing.Color.Transparent;
            this.btnPurchases.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnPurchases.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnPurchases.BackgroundImage")));
            this.btnPurchases.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnPurchases.ButtonText = "Purchases";
            this.btnPurchases.ButtonTextMarginLeft = 0;
            this.btnPurchases.ColorContrastOnClick = 45;
            this.btnPurchases.ColorContrastOnHover = 45;
            this.btnPurchases.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btnPurchases.CustomizableEdges = borderEdges3;
            this.btnPurchases.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnPurchases.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnPurchases.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnPurchases.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnPurchases.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnPurchases.Font = new System.Drawing.Font("Segoe UI Semibold", 9.792F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnPurchases.ForeColor = System.Drawing.Color.White;
            this.btnPurchases.IconLeft = null;
            this.btnPurchases.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnPurchases.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnPurchases.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnPurchases.IconMarginLeft = 11;
            this.btnPurchases.IconPadding = 10;
            this.btnPurchases.IconRight = null;
            this.btnPurchases.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnPurchases.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnPurchases.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnPurchases.IconSize = 25;
            this.btnPurchases.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnPurchases.IdleBorderRadius = 0;
            this.btnPurchases.IdleBorderThickness = 0;
            this.btnPurchases.IdleFillColor = System.Drawing.Color.Empty;
            this.btnPurchases.IdleIconLeftImage = null;
            this.btnPurchases.IdleIconRightImage = null;
            this.btnPurchases.IndicateFocus = false;
            this.btnPurchases.Location = new System.Drawing.Point(20, 726);
            this.btnPurchases.Name = "btnPurchases";
            this.btnPurchases.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnPurchases.OnDisabledState.BorderRadius = 15;
            this.btnPurchases.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnPurchases.OnDisabledState.BorderThickness = 1;
            this.btnPurchases.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnPurchases.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnPurchases.OnDisabledState.IconLeftImage = null;
            this.btnPurchases.OnDisabledState.IconRightImage = null;
            this.btnPurchases.onHoverState.BorderColor = System.Drawing.Color.Transparent;
            this.btnPurchases.onHoverState.BorderRadius = 15;
            this.btnPurchases.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnPurchases.onHoverState.BorderThickness = 1;
            this.btnPurchases.onHoverState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnPurchases.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnPurchases.onHoverState.IconLeftImage = null;
            this.btnPurchases.onHoverState.IconRightImage = null;
            this.btnPurchases.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btnPurchases.OnIdleState.BorderRadius = 15;
            this.btnPurchases.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnPurchases.OnIdleState.BorderThickness = 1;
            this.btnPurchases.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btnPurchases.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnPurchases.OnIdleState.IconLeftImage = null;
            this.btnPurchases.OnIdleState.IconRightImage = null;
            this.btnPurchases.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnPurchases.OnPressedState.BorderRadius = 15;
            this.btnPurchases.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnPurchases.OnPressedState.BorderThickness = 1;
            this.btnPurchases.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnPurchases.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnPurchases.OnPressedState.IconLeftImage = null;
            this.btnPurchases.OnPressedState.IconRightImage = null;
            this.btnPurchases.Size = new System.Drawing.Size(235, 42);
            this.btnPurchases.TabIndex = 13;
            this.btnPurchases.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnPurchases.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnPurchases.TextMarginLeft = 0;
            this.btnPurchases.TextPadding = new System.Windows.Forms.Padding(15, 0, 0, 0);
            this.btnPurchases.UseDefaultRadiusAndThickness = true;
            // 
            // btnSales
            // 
            this.btnSales.AllowAnimations = true;
            this.btnSales.AllowMouseEffects = true;
            this.btnSales.AllowToggling = false;
            this.btnSales.AnimationSpeed = 200;
            this.btnSales.AutoGenerateColors = false;
            this.btnSales.AutoRoundBorders = false;
            this.btnSales.AutoSizeLeftIcon = true;
            this.btnSales.AutoSizeRightIcon = true;
            this.btnSales.BackColor = System.Drawing.Color.Transparent;
            this.btnSales.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnSales.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnSales.BackgroundImage")));
            this.btnSales.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSales.ButtonText = "Sales";
            this.btnSales.ButtonTextMarginLeft = 0;
            this.btnSales.ColorContrastOnClick = 45;
            this.btnSales.ColorContrastOnHover = 45;
            this.btnSales.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.btnSales.CustomizableEdges = borderEdges4;
            this.btnSales.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnSales.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSales.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnSales.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnSales.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnSales.Font = new System.Drawing.Font("Segoe UI Semibold", 9.792F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnSales.ForeColor = System.Drawing.Color.White;
            this.btnSales.IconLeft = null;
            this.btnSales.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnSales.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnSales.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnSales.IconMarginLeft = 11;
            this.btnSales.IconPadding = 10;
            this.btnSales.IconRight = null;
            this.btnSales.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnSales.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnSales.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnSales.IconSize = 25;
            this.btnSales.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnSales.IdleBorderRadius = 0;
            this.btnSales.IdleBorderThickness = 0;
            this.btnSales.IdleFillColor = System.Drawing.Color.Empty;
            this.btnSales.IdleIconLeftImage = null;
            this.btnSales.IdleIconRightImage = null;
            this.btnSales.IndicateFocus = false;
            this.btnSales.Location = new System.Drawing.Point(20, 668);
            this.btnSales.Name = "btnSales";
            this.btnSales.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSales.OnDisabledState.BorderRadius = 15;
            this.btnSales.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSales.OnDisabledState.BorderThickness = 1;
            this.btnSales.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSales.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSales.OnDisabledState.IconLeftImage = null;
            this.btnSales.OnDisabledState.IconRightImage = null;
            this.btnSales.onHoverState.BorderColor = System.Drawing.Color.Transparent;
            this.btnSales.onHoverState.BorderRadius = 15;
            this.btnSales.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSales.onHoverState.BorderThickness = 1;
            this.btnSales.onHoverState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnSales.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnSales.onHoverState.IconLeftImage = null;
            this.btnSales.onHoverState.IconRightImage = null;
            this.btnSales.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btnSales.OnIdleState.BorderRadius = 15;
            this.btnSales.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSales.OnIdleState.BorderThickness = 1;
            this.btnSales.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btnSales.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnSales.OnIdleState.IconLeftImage = null;
            this.btnSales.OnIdleState.IconRightImage = null;
            this.btnSales.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnSales.OnPressedState.BorderRadius = 15;
            this.btnSales.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSales.OnPressedState.BorderThickness = 1;
            this.btnSales.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnSales.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnSales.OnPressedState.IconLeftImage = null;
            this.btnSales.OnPressedState.IconRightImage = null;
            this.btnSales.Size = new System.Drawing.Size(235, 42);
            this.btnSales.TabIndex = 12;
            this.btnSales.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnSales.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnSales.TextMarginLeft = 0;
            this.btnSales.TextPadding = new System.Windows.Forms.Padding(15, 0, 0, 0);
            this.btnSales.UseDefaultRadiusAndThickness = true;
            // 
            // bunifuLabel6
            // 
            this.bunifuLabel6.AllowParentOverrides = false;
            this.bunifuLabel6.AutoEllipsis = false;
            this.bunifuLabel6.CursorType = null;
            this.bunifuLabel6.Font = new System.Drawing.Font("Segoe UI", 12.096F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel6.ForeColor = System.Drawing.Color.Gainsboro;
            this.bunifuLabel6.Location = new System.Drawing.Point(20, 621);
            this.bunifuLabel6.Name = "bunifuLabel6";
            this.bunifuLabel6.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel6.Size = new System.Drawing.Size(108, 28);
            this.bunifuLabel6.TabIndex = 11;
            this.bunifuLabel6.Text = "Transactions";
            this.bunifuLabel6.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel6.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // btnStkAdj
            // 
            this.btnStkAdj.AllowAnimations = true;
            this.btnStkAdj.AllowMouseEffects = true;
            this.btnStkAdj.AllowToggling = false;
            this.btnStkAdj.AnimationSpeed = 200;
            this.btnStkAdj.AutoGenerateColors = false;
            this.btnStkAdj.AutoRoundBorders = false;
            this.btnStkAdj.AutoSizeLeftIcon = true;
            this.btnStkAdj.AutoSizeRightIcon = true;
            this.btnStkAdj.BackColor = System.Drawing.Color.Transparent;
            this.btnStkAdj.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnStkAdj.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnStkAdj.BackgroundImage")));
            this.btnStkAdj.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnStkAdj.ButtonText = "Stock Adjustment";
            this.btnStkAdj.ButtonTextMarginLeft = 0;
            this.btnStkAdj.ColorContrastOnClick = 45;
            this.btnStkAdj.ColorContrastOnHover = 45;
            this.btnStkAdj.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.btnStkAdj.CustomizableEdges = borderEdges5;
            this.btnStkAdj.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnStkAdj.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnStkAdj.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnStkAdj.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnStkAdj.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnStkAdj.Font = new System.Drawing.Font("Segoe UI Semibold", 9.792F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnStkAdj.ForeColor = System.Drawing.Color.White;
            this.btnStkAdj.IconLeft = null;
            this.btnStkAdj.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnStkAdj.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnStkAdj.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnStkAdj.IconMarginLeft = 11;
            this.btnStkAdj.IconPadding = 10;
            this.btnStkAdj.IconRight = null;
            this.btnStkAdj.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnStkAdj.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnStkAdj.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnStkAdj.IconSize = 25;
            this.btnStkAdj.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnStkAdj.IdleBorderRadius = 0;
            this.btnStkAdj.IdleBorderThickness = 0;
            this.btnStkAdj.IdleFillColor = System.Drawing.Color.Empty;
            this.btnStkAdj.IdleIconLeftImage = null;
            this.btnStkAdj.IdleIconRightImage = null;
            this.btnStkAdj.IndicateFocus = false;
            this.btnStkAdj.Location = new System.Drawing.Point(20, 556);
            this.btnStkAdj.Name = "btnStkAdj";
            this.btnStkAdj.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnStkAdj.OnDisabledState.BorderRadius = 15;
            this.btnStkAdj.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnStkAdj.OnDisabledState.BorderThickness = 1;
            this.btnStkAdj.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnStkAdj.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnStkAdj.OnDisabledState.IconLeftImage = null;
            this.btnStkAdj.OnDisabledState.IconRightImage = null;
            this.btnStkAdj.onHoverState.BorderColor = System.Drawing.Color.Transparent;
            this.btnStkAdj.onHoverState.BorderRadius = 15;
            this.btnStkAdj.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnStkAdj.onHoverState.BorderThickness = 1;
            this.btnStkAdj.onHoverState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnStkAdj.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnStkAdj.onHoverState.IconLeftImage = null;
            this.btnStkAdj.onHoverState.IconRightImage = null;
            this.btnStkAdj.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btnStkAdj.OnIdleState.BorderRadius = 15;
            this.btnStkAdj.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnStkAdj.OnIdleState.BorderThickness = 1;
            this.btnStkAdj.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btnStkAdj.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnStkAdj.OnIdleState.IconLeftImage = null;
            this.btnStkAdj.OnIdleState.IconRightImage = null;
            this.btnStkAdj.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnStkAdj.OnPressedState.BorderRadius = 15;
            this.btnStkAdj.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnStkAdj.OnPressedState.BorderThickness = 1;
            this.btnStkAdj.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnStkAdj.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnStkAdj.OnPressedState.IconLeftImage = null;
            this.btnStkAdj.OnPressedState.IconRightImage = null;
            this.btnStkAdj.Size = new System.Drawing.Size(235, 42);
            this.btnStkAdj.TabIndex = 10;
            this.btnStkAdj.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnStkAdj.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnStkAdj.TextMarginLeft = 0;
            this.btnStkAdj.TextPadding = new System.Windows.Forms.Padding(15, 0, 0, 0);
            this.btnStkAdj.UseDefaultRadiusAndThickness = true;
            // 
            // btnSup
            // 
            this.btnSup.AllowAnimations = true;
            this.btnSup.AllowMouseEffects = true;
            this.btnSup.AllowToggling = false;
            this.btnSup.AnimationSpeed = 200;
            this.btnSup.AutoGenerateColors = false;
            this.btnSup.AutoRoundBorders = false;
            this.btnSup.AutoSizeLeftIcon = true;
            this.btnSup.AutoSizeRightIcon = true;
            this.btnSup.BackColor = System.Drawing.Color.Transparent;
            this.btnSup.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnSup.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnSup.BackgroundImage")));
            this.btnSup.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSup.ButtonText = "Suppliers";
            this.btnSup.ButtonTextMarginLeft = 0;
            this.btnSup.ColorContrastOnClick = 45;
            this.btnSup.ColorContrastOnHover = 45;
            this.btnSup.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.btnSup.CustomizableEdges = borderEdges6;
            this.btnSup.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnSup.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSup.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnSup.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnSup.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnSup.Font = new System.Drawing.Font("Segoe UI Semibold", 9.792F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnSup.ForeColor = System.Drawing.Color.White;
            this.btnSup.IconLeft = null;
            this.btnSup.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnSup.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnSup.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnSup.IconMarginLeft = 11;
            this.btnSup.IconPadding = 10;
            this.btnSup.IconRight = null;
            this.btnSup.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnSup.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnSup.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnSup.IconSize = 25;
            this.btnSup.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnSup.IdleBorderRadius = 0;
            this.btnSup.IdleBorderThickness = 0;
            this.btnSup.IdleFillColor = System.Drawing.Color.Empty;
            this.btnSup.IdleIconLeftImage = null;
            this.btnSup.IdleIconRightImage = null;
            this.btnSup.IndicateFocus = false;
            this.btnSup.Location = new System.Drawing.Point(20, 497);
            this.btnSup.Name = "btnSup";
            this.btnSup.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSup.OnDisabledState.BorderRadius = 15;
            this.btnSup.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSup.OnDisabledState.BorderThickness = 1;
            this.btnSup.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSup.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSup.OnDisabledState.IconLeftImage = null;
            this.btnSup.OnDisabledState.IconRightImage = null;
            this.btnSup.onHoverState.BorderColor = System.Drawing.Color.Transparent;
            this.btnSup.onHoverState.BorderRadius = 15;
            this.btnSup.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSup.onHoverState.BorderThickness = 1;
            this.btnSup.onHoverState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnSup.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnSup.onHoverState.IconLeftImage = null;
            this.btnSup.onHoverState.IconRightImage = null;
            this.btnSup.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btnSup.OnIdleState.BorderRadius = 15;
            this.btnSup.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSup.OnIdleState.BorderThickness = 1;
            this.btnSup.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btnSup.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnSup.OnIdleState.IconLeftImage = null;
            this.btnSup.OnIdleState.IconRightImage = null;
            this.btnSup.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnSup.OnPressedState.BorderRadius = 15;
            this.btnSup.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSup.OnPressedState.BorderThickness = 1;
            this.btnSup.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnSup.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnSup.OnPressedState.IconLeftImage = null;
            this.btnSup.OnPressedState.IconRightImage = null;
            this.btnSup.Size = new System.Drawing.Size(235, 42);
            this.btnSup.TabIndex = 9;
            this.btnSup.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnSup.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnSup.TextMarginLeft = 0;
            this.btnSup.TextPadding = new System.Windows.Forms.Padding(15, 0, 0, 0);
            this.btnSup.UseDefaultRadiusAndThickness = true;
            // 
            // btnProd
            // 
            this.btnProd.AllowAnimations = true;
            this.btnProd.AllowMouseEffects = true;
            this.btnProd.AllowToggling = false;
            this.btnProd.AnimationSpeed = 200;
            this.btnProd.AutoGenerateColors = false;
            this.btnProd.AutoRoundBorders = false;
            this.btnProd.AutoSizeLeftIcon = true;
            this.btnProd.AutoSizeRightIcon = true;
            this.btnProd.BackColor = System.Drawing.Color.Transparent;
            this.btnProd.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnProd.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnProd.BackgroundImage")));
            this.btnProd.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnProd.ButtonText = "Products";
            this.btnProd.ButtonTextMarginLeft = 0;
            this.btnProd.ColorContrastOnClick = 45;
            this.btnProd.ColorContrastOnHover = 45;
            this.btnProd.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.btnProd.CustomizableEdges = borderEdges7;
            this.btnProd.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnProd.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnProd.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnProd.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnProd.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnProd.Font = new System.Drawing.Font("Segoe UI Semibold", 9.792F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnProd.ForeColor = System.Drawing.Color.White;
            this.btnProd.IconLeft = null;
            this.btnProd.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnProd.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnProd.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnProd.IconMarginLeft = 11;
            this.btnProd.IconPadding = 10;
            this.btnProd.IconRight = null;
            this.btnProd.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnProd.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnProd.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnProd.IconSize = 25;
            this.btnProd.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnProd.IdleBorderRadius = 0;
            this.btnProd.IdleBorderThickness = 0;
            this.btnProd.IdleFillColor = System.Drawing.Color.Empty;
            this.btnProd.IdleIconLeftImage = null;
            this.btnProd.IdleIconRightImage = null;
            this.btnProd.IndicateFocus = false;
            this.btnProd.Location = new System.Drawing.Point(20, 439);
            this.btnProd.Name = "btnProd";
            this.btnProd.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnProd.OnDisabledState.BorderRadius = 15;
            this.btnProd.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnProd.OnDisabledState.BorderThickness = 1;
            this.btnProd.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnProd.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnProd.OnDisabledState.IconLeftImage = null;
            this.btnProd.OnDisabledState.IconRightImage = null;
            this.btnProd.onHoverState.BorderColor = System.Drawing.Color.Transparent;
            this.btnProd.onHoverState.BorderRadius = 15;
            this.btnProd.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnProd.onHoverState.BorderThickness = 1;
            this.btnProd.onHoverState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnProd.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnProd.onHoverState.IconLeftImage = null;
            this.btnProd.onHoverState.IconRightImage = null;
            this.btnProd.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btnProd.OnIdleState.BorderRadius = 15;
            this.btnProd.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnProd.OnIdleState.BorderThickness = 1;
            this.btnProd.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btnProd.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnProd.OnIdleState.IconLeftImage = null;
            this.btnProd.OnIdleState.IconRightImage = null;
            this.btnProd.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnProd.OnPressedState.BorderRadius = 15;
            this.btnProd.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnProd.OnPressedState.BorderThickness = 1;
            this.btnProd.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnProd.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnProd.OnPressedState.IconLeftImage = null;
            this.btnProd.OnPressedState.IconRightImage = null;
            this.btnProd.Size = new System.Drawing.Size(235, 42);
            this.btnProd.TabIndex = 8;
            this.btnProd.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnProd.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnProd.TextMarginLeft = 0;
            this.btnProd.TextPadding = new System.Windows.Forms.Padding(15, 0, 0, 0);
            this.btnProd.UseDefaultRadiusAndThickness = true;
            // 
            // bunifuLabel5
            // 
            this.bunifuLabel5.AllowParentOverrides = false;
            this.bunifuLabel5.AutoEllipsis = false;
            this.bunifuLabel5.CursorType = null;
            this.bunifuLabel5.Font = new System.Drawing.Font("Segoe UI", 12.096F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel5.ForeColor = System.Drawing.Color.Gainsboro;
            this.bunifuLabel5.Location = new System.Drawing.Point(20, 392);
            this.bunifuLabel5.Name = "bunifuLabel5";
            this.bunifuLabel5.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel5.Size = new System.Drawing.Size(83, 28);
            this.bunifuLabel5.TabIndex = 7;
            this.bunifuLabel5.Text = "Inventory";
            this.bunifuLabel5.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel5.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // btnEmp
            // 
            this.btnEmp.AllowAnimations = true;
            this.btnEmp.AllowMouseEffects = true;
            this.btnEmp.AllowToggling = false;
            this.btnEmp.AnimationSpeed = 200;
            this.btnEmp.AutoGenerateColors = false;
            this.btnEmp.AutoRoundBorders = false;
            this.btnEmp.AutoSizeLeftIcon = true;
            this.btnEmp.AutoSizeRightIcon = true;
            this.btnEmp.BackColor = System.Drawing.Color.Transparent;
            this.btnEmp.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnEmp.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnEmp.BackgroundImage")));
            this.btnEmp.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnEmp.ButtonText = "Employees";
            this.btnEmp.ButtonTextMarginLeft = 0;
            this.btnEmp.ColorContrastOnClick = 45;
            this.btnEmp.ColorContrastOnHover = 45;
            this.btnEmp.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges8.BottomLeft = true;
            borderEdges8.BottomRight = true;
            borderEdges8.TopLeft = true;
            borderEdges8.TopRight = true;
            this.btnEmp.CustomizableEdges = borderEdges8;
            this.btnEmp.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnEmp.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnEmp.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnEmp.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnEmp.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnEmp.Font = new System.Drawing.Font("Segoe UI Semibold", 9.792F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnEmp.ForeColor = System.Drawing.Color.White;
            this.btnEmp.IconLeft = null;
            this.btnEmp.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnEmp.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnEmp.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnEmp.IconMarginLeft = 11;
            this.btnEmp.IconPadding = 10;
            this.btnEmp.IconRight = null;
            this.btnEmp.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnEmp.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnEmp.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnEmp.IconSize = 25;
            this.btnEmp.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnEmp.IdleBorderRadius = 0;
            this.btnEmp.IdleBorderThickness = 0;
            this.btnEmp.IdleFillColor = System.Drawing.Color.Empty;
            this.btnEmp.IdleIconLeftImage = null;
            this.btnEmp.IdleIconRightImage = null;
            this.btnEmp.IndicateFocus = false;
            this.btnEmp.Location = new System.Drawing.Point(20, 314);
            this.btnEmp.Name = "btnEmp";
            this.btnEmp.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnEmp.OnDisabledState.BorderRadius = 15;
            this.btnEmp.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnEmp.OnDisabledState.BorderThickness = 1;
            this.btnEmp.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnEmp.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnEmp.OnDisabledState.IconLeftImage = null;
            this.btnEmp.OnDisabledState.IconRightImage = null;
            this.btnEmp.onHoverState.BorderColor = System.Drawing.Color.Transparent;
            this.btnEmp.onHoverState.BorderRadius = 15;
            this.btnEmp.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnEmp.onHoverState.BorderThickness = 1;
            this.btnEmp.onHoverState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnEmp.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnEmp.onHoverState.IconLeftImage = null;
            this.btnEmp.onHoverState.IconRightImage = null;
            this.btnEmp.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btnEmp.OnIdleState.BorderRadius = 15;
            this.btnEmp.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnEmp.OnIdleState.BorderThickness = 1;
            this.btnEmp.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btnEmp.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnEmp.OnIdleState.IconLeftImage = null;
            this.btnEmp.OnIdleState.IconRightImage = null;
            this.btnEmp.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnEmp.OnPressedState.BorderRadius = 15;
            this.btnEmp.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnEmp.OnPressedState.BorderThickness = 1;
            this.btnEmp.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnEmp.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnEmp.OnPressedState.IconLeftImage = null;
            this.btnEmp.OnPressedState.IconRightImage = null;
            this.btnEmp.Size = new System.Drawing.Size(235, 42);
            this.btnEmp.TabIndex = 6;
            this.btnEmp.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnEmp.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnEmp.TextMarginLeft = 0;
            this.btnEmp.TextPadding = new System.Windows.Forms.Padding(15, 0, 0, 0);
            this.btnEmp.UseDefaultRadiusAndThickness = true;
            // 
            // bunifuLabel4
            // 
            this.bunifuLabel4.AllowParentOverrides = false;
            this.bunifuLabel4.AutoEllipsis = false;
            this.bunifuLabel4.CursorType = null;
            this.bunifuLabel4.Font = new System.Drawing.Font("Segoe UI", 12.096F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel4.ForeColor = System.Drawing.Color.Gainsboro;
            this.bunifuLabel4.Location = new System.Drawing.Point(20, 267);
            this.bunifuLabel4.Name = "bunifuLabel4";
            this.bunifuLabel4.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel4.Size = new System.Drawing.Size(155, 28);
            this.bunifuLabel4.TabIndex = 5;
            this.bunifuLabel4.Text = "Human Resources";
            this.bunifuLabel4.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel4.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // btnDashboard
            // 
            this.btnDashboard.AllowAnimations = true;
            this.btnDashboard.AllowMouseEffects = true;
            this.btnDashboard.AllowToggling = false;
            this.btnDashboard.AnimationSpeed = 200;
            this.btnDashboard.AutoGenerateColors = false;
            this.btnDashboard.AutoRoundBorders = false;
            this.btnDashboard.AutoSizeLeftIcon = true;
            this.btnDashboard.AutoSizeRightIcon = true;
            this.btnDashboard.BackColor = System.Drawing.Color.Transparent;
            this.btnDashboard.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnDashboard.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnDashboard.BackgroundImage")));
            this.btnDashboard.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDashboard.ButtonText = "DashBoard";
            this.btnDashboard.ButtonTextMarginLeft = 0;
            this.btnDashboard.ColorContrastOnClick = 45;
            this.btnDashboard.ColorContrastOnHover = 45;
            this.btnDashboard.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges9.BottomLeft = true;
            borderEdges9.BottomRight = true;
            borderEdges9.TopLeft = true;
            borderEdges9.TopRight = true;
            this.btnDashboard.CustomizableEdges = borderEdges9;
            this.btnDashboard.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnDashboard.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnDashboard.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnDashboard.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnDashboard.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnDashboard.Font = new System.Drawing.Font("Segoe UI Semibold", 9.792F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnDashboard.ForeColor = System.Drawing.Color.White;
            this.btnDashboard.IconLeft = null;
            this.btnDashboard.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnDashboard.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnDashboard.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnDashboard.IconMarginLeft = 11;
            this.btnDashboard.IconPadding = 10;
            this.btnDashboard.IconRight = null;
            this.btnDashboard.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnDashboard.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnDashboard.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnDashboard.IconSize = 25;
            this.btnDashboard.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnDashboard.IdleBorderRadius = 0;
            this.btnDashboard.IdleBorderThickness = 0;
            this.btnDashboard.IdleFillColor = System.Drawing.Color.Empty;
            this.btnDashboard.IdleIconLeftImage = null;
            this.btnDashboard.IdleIconRightImage = null;
            this.btnDashboard.IndicateFocus = false;
            this.btnDashboard.Location = new System.Drawing.Point(20, 191);
            this.btnDashboard.Name = "btnDashboard";
            this.btnDashboard.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnDashboard.OnDisabledState.BorderRadius = 15;
            this.btnDashboard.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDashboard.OnDisabledState.BorderThickness = 1;
            this.btnDashboard.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnDashboard.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnDashboard.OnDisabledState.IconLeftImage = null;
            this.btnDashboard.OnDisabledState.IconRightImage = null;
            this.btnDashboard.onHoverState.BorderColor = System.Drawing.Color.Transparent;
            this.btnDashboard.onHoverState.BorderRadius = 15;
            this.btnDashboard.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDashboard.onHoverState.BorderThickness = 1;
            this.btnDashboard.onHoverState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnDashboard.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnDashboard.onHoverState.IconLeftImage = null;
            this.btnDashboard.onHoverState.IconRightImage = null;
            this.btnDashboard.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btnDashboard.OnIdleState.BorderRadius = 15;
            this.btnDashboard.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDashboard.OnIdleState.BorderThickness = 1;
            this.btnDashboard.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btnDashboard.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnDashboard.OnIdleState.IconLeftImage = null;
            this.btnDashboard.OnIdleState.IconRightImage = null;
            this.btnDashboard.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnDashboard.OnPressedState.BorderRadius = 15;
            this.btnDashboard.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDashboard.OnPressedState.BorderThickness = 1;
            this.btnDashboard.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnDashboard.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnDashboard.OnPressedState.IconLeftImage = null;
            this.btnDashboard.OnPressedState.IconRightImage = null;
            this.btnDashboard.Size = new System.Drawing.Size(235, 42);
            this.btnDashboard.TabIndex = 4;
            this.btnDashboard.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnDashboard.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnDashboard.TextMarginLeft = 0;
            this.btnDashboard.TextPadding = new System.Windows.Forms.Padding(15, 0, 0, 0);
            this.btnDashboard.UseDefaultRadiusAndThickness = true;
            // 
            // bunifuSeparator1
            // 
            this.bunifuSeparator1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuSeparator1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuSeparator1.BackgroundImage")));
            this.bunifuSeparator1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuSeparator1.DashCap = Bunifu.UI.WinForms.BunifuSeparator.CapStyles.Flat;
            this.bunifuSeparator1.LineColor = System.Drawing.Color.DarkGray;
            this.bunifuSeparator1.LineStyle = Bunifu.UI.WinForms.BunifuSeparator.LineStyles.Solid;
            this.bunifuSeparator1.LineThickness = 1;
            this.bunifuSeparator1.Location = new System.Drawing.Point(19, 120);
            this.bunifuSeparator1.Margin = new System.Windows.Forms.Padding(5, 4, 5, 4);
            this.bunifuSeparator1.Name = "bunifuSeparator1";
            this.bunifuSeparator1.Orientation = Bunifu.UI.WinForms.BunifuSeparator.LineOrientation.Horizontal;
            this.bunifuSeparator1.Size = new System.Drawing.Size(236, 17);
            this.bunifuSeparator1.TabIndex = 3;
            // 
            // bunifuLabel3
            // 
            this.bunifuLabel3.AllowParentOverrides = false;
            this.bunifuLabel3.AutoEllipsis = false;
            this.bunifuLabel3.CursorType = null;
            this.bunifuLabel3.Font = new System.Drawing.Font("Segoe UI", 12.096F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel3.ForeColor = System.Drawing.Color.Gainsboro;
            this.bunifuLabel3.Location = new System.Drawing.Point(20, 144);
            this.bunifuLabel3.Name = "bunifuLabel3";
            this.bunifuLabel3.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel3.Size = new System.Drawing.Size(44, 28);
            this.bunifuLabel3.TabIndex = 2;
            this.bunifuLabel3.Text = "Main";
            this.bunifuLabel3.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel3.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel2
            // 
            this.bunifuLabel2.AllowParentOverrides = false;
            this.bunifuLabel2.AutoEllipsis = false;
            this.bunifuLabel2.CursorType = null;
            this.bunifuLabel2.Font = new System.Drawing.Font("Segoe UI", 12.096F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel2.ForeColor = System.Drawing.Color.Gainsboro;
            this.bunifuLabel2.Location = new System.Drawing.Point(20, 72);
            this.bunifuLabel2.Name = "bunifuLabel2";
            this.bunifuLabel2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel2.Size = new System.Drawing.Size(101, 28);
            this.bunifuLabel2.TabIndex = 1;
            this.bunifuLabel2.Text = "ERP System";
            this.bunifuLabel2.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Segoe UI", 16.128F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel1.ForeColor = System.Drawing.Color.White;
            this.bunifuLabel1.Location = new System.Drawing.Point(20, 28);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(197, 37);
            this.bunifuLabel1.TabIndex = 0;
            this.bunifuLabel1.Text = "ASM Enterprise";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // SideNavBar
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this.bunifuPanel1);
            this.Name = "SideNavBar";
            this.Size = new System.Drawing.Size(305, 1032);
            this.bunifuPanel1.ResumeLayout(false);
            this.bunifuPanel1.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuSeparator bunifuSeparator1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel3;
        public Bunifu.UI.WinForms.BunifuButton.BunifuButton btnDashboard;
        public Bunifu.UI.WinForms.BunifuLabel bunifuLabel4;
        public Bunifu.UI.WinForms.BunifuButton.BunifuButton btnProd;
        public Bunifu.UI.WinForms.BunifuLabel bunifuLabel5;
        public Bunifu.UI.WinForms.BunifuButton.BunifuButton btnStkAdj;
        public Bunifu.UI.WinForms.BunifuButton.BunifuButton btnSup;
        public Bunifu.UI.WinForms.BunifuButton.BunifuButton btnEmp;
        public Bunifu.UI.WinForms.BunifuButton.BunifuButton btnHistory;
        public Bunifu.UI.WinForms.BunifuButton.BunifuButton btnPurchases;
        public Bunifu.UI.WinForms.BunifuButton.BunifuButton btnSales;
        public Bunifu.UI.WinForms.BunifuLabel bunifuLabel6;
        private Bunifu.UI.WinForms.BunifuSeparator bunifuSeparator5;
        private Bunifu.UI.WinForms.BunifuSeparator bunifuSeparator4;
        private Bunifu.UI.WinForms.BunifuSeparator bunifuSeparator3;
        private Bunifu.UI.WinForms.BunifuSeparator bunifuSeparator2;
        public Bunifu.UI.WinForms.BunifuButton.BunifuButton btnUserProfile;
    }
}
